//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/json","dojo/_base/Deferred","dojo/has","esri/kernel","esri/request","esri/deferredUtils","esri/tasks/Task","esri/geometry/Extent","esri/geometry/Polyline","esri/geometry/Polygon","esri/geometry/Multipoint","esri/geometry/jsonUtils"],function(u,m,s,k,n,A,B,p,q,y,w,x,v,z,r){u=u(y,{declaredClass:"esri.tasks.GeometryService",_eventMap:{"areas-and-lengths-complete":["result"],"auto-complete-complete":["geometries"],"buffer-complete":["geometries"],
"convex-hull-complete":["geometry"],"cut-complete":["result"],"difference-complete":["geometries"],"distance-complete":["distance"],"generalize-complete":["geometries"],"intersect-complete":["geometries"],"label-points-complete":["geometries"],"lengths-complete":["result"],"offset-complete":["geometries"],"project-complete":["geometries"],"relation-complete":["relations"],"reshape-complete":["geometry"],"simplify-complete":["geometries"],"trim-extend-complete":["geometries"],"union-complete":["geometry"]},
constructor:function(a){a=m.hitch;this._projectHandler=a(this,this._projectHandler);this._simplifyHandler=a(this,this._simplifyHandler);this._bufferHandler=a(this,this._bufferHandler);this._areasAndLengthsHandler=a(this,this._areasAndLengthsHandler);this._lengthsHandler=a(this,this._lengthsHandler);this._labelPointsHandler=a(this,this._labelPointsHandler);this._relationHandler=a(this,this._relationHandler);this._convexHullHandler=a(this,this._convexHullHandler);this._unionHandler=a(this,this._unionHandler);
this._autoCompleteHandler=a(this,this._autoCompleteHandler);this._reshapeHandler=a(this,this._reshapeHandler);this._cutHandler=a(this,this._cutHandler);this._intersectHandler=a(this,this._intersectHandler);this._differenceHandler=a(this,this._differenceHandler);this._trimExtendHandler=a(this,this._trimExtendHandler);this._densifyHandler=a(this,this._densifyHandler);this._generalizeHandler=a(this,this._densifyHandler);this._offsetHandler=a(this,this._offsetHandler);this._distanceHandler=a(this,this._distanceHandler);
this.registerConnectEvents()},_encodeGeometries:function(a){var h=[],e,d=a.length;for(e=0;e<d;e++)h.push(a[e].toJson());return{geometryType:r.getJsonType(a[0]),geometries:h}},_decodeGeometries:function(a,h,e){var d=r.getGeometryType(h);a=a.geometries;var g=[],c={spatialReference:e.toJson()},f=m.mixin;s.forEach(a,function(a,e){g[e]=new d(f(a,c))});return g},_toProjectGeometry:function(a){var h=a.spatialReference.toJson();return a instanceof w?new v({rings:[[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,
a.ymax],[a.xmax,a.ymin],[a.xmin,a.ymin]]],spatialReference:h}):new x({paths:[[].concat(a.points)],spatialReference:h})},_fromProjectedGeometry:function(a,h,e){return"esriGeometryEnvelope"===h?(a=a.rings[0],new w(a[0][0],a[0][1],a[2][0],a[2][1],e)):new z({points:a.paths[0],spatialReference:e.toJson()})},project:function(a,h,e,d){var g=m.mixin({},this._url.query,{f:"json"}),c;a.geometries?(d=e,e=h,h=a.outSR,c=a.geometries[0],g=m.mixin(g,a.toJson())):(c=a[0],g=m.mixin(g,{outSR:h.wkid||k.toJson(h.toJson()),
inSR:c.spatialReference.wkid||k.toJson(c.spatialReference.toJson()),geometries:k.toJson(this._encodeGeometries(a))}));var f=r.getJsonType(c),b=this._projectHandler,l=this._errorHandler,t=new n(q._dfdCanceller);t._pendingDfd=p({url:this._url.path+"/project",content:g,callbackParamName:"callback",load:function(a,c){b(a,c,f,h,e,d,t)},error:function(a){l(a,d,t)}});return t},_projectHandler:function(a,h,e,d,g,c,f){try{var b=this._decodeGeometries(a,e,d);this._successHandler([b],"onProjectComplete",g,f)}catch(l){this._errorHandler(l,
c,f)}},onProjectComplete:function(){},simplify:function(a,h,e){var d=a[0].spatialReference,g=m.mixin({},this._url.query,{f:"json",sr:d.wkid?d.wkid:k.toJson(d.toJson()),geometries:k.toJson(this._encodeGeometries(a))}),c=r.getJsonType(a[0]),f=this._simplifyHandler,b=this._errorHandler,l=new n(q._dfdCanceller);l._pendingDfd=p({url:this._url.path+"/simplify",content:g,callbackParamName:"callback",load:function(a,b){f(a,b,c,d,h,e,l)},error:function(a){b(a,e,l)}});return l},_simplifyHandler:function(a,
h,e,d,g,c,f){try{var b=this._decodeGeometries(a,e,d);this._successHandler([b],"onSimplifyComplete",g,f)}catch(l){this._errorHandler(l,c,f)}},onSimplifyComplete:function(){},convexHull:function(a,h,e){var d=a[0].spatialReference;a=m.mixin({},this._url.query,{f:"json",sr:k.toJson(d.toJson()),geometries:k.toJson(this._encodeGeometries(a))});var g=this._convexHullHandler,c=this._errorHandler,f=new n(q._dfdCanceller);f._pendingDfd=p({url:this._url.path+"/convexHull",content:a,callbackParamName:"callback",
load:function(a,c){g(a,c,d,h,e,f)},error:function(a){c(a,e,f)}});return f},_convexHullHandler:function(a,h,e,d,g,c){try{var f=r.fromJson(a.geometry).setSpatialReference(e);this._successHandler([f],"onConvexHullComplete",d,c)}catch(b){this._errorHandler(b,g,c)}},onConvexHullComplete:function(){},union:function(a,h,e){var d=a[0].spatialReference;a=m.mixin({},this._url.query,{f:"json",sr:k.toJson(d.toJson()),geometries:k.toJson(this._encodeGeometries(a))});var g=this._unionHandler,c=this._errorHandler,
f=new n(q._dfdCanceller);f._pendingDfd=p({url:this._url.path+"/union",content:a,callbackParamName:"callback",load:function(a,c){g(a,c,d,h,e,f)},error:function(a){c(a,e,f)}});return f},_unionHandler:function(a,h,e,d,g,c){try{var f=r.fromJson(a.geometry).setSpatialReference(e);this._successHandler([f],"onUnionComplete",d,c)}catch(b){this._errorHandler(b,g,c)}},onUnionComplete:function(){},autoComplete:function(a,h,e,d){var g=a[0].spatialReference;a=m.mixin({},this._url.query,{f:"json",sr:k.toJson(g.toJson()),
polygons:k.toJson(this._encodeGeometries(a).geometries),polylines:k.toJson(this._encodeGeometries(h).geometries)});var c=this._autoCompleteHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/autoComplete",content:a,callbackParamName:"callback",load:function(a,f){c(a,f,g,e,d,b)},error:function(a){f(a,d,b)}});return b},_autoCompleteHandler:function(a,h,e,d,g,c){try{var f=a.geometries;a=[];var b,l=f.length;for(b=0;b<l;b++)a[b]=new v({spatialReference:e,rings:f[b].rings});
this._successHandler([a],"onAutoCompleteComplete",d,c)}catch(t){this._errorHandler(t,g,c)}},onAutoCompleteComplete:function(){},reshape:function(a,h,e,d){var g=a.spatialReference;a=m.mixin({},this._url.query,{f:"json",sr:k.toJson(g.toJson()),target:k.toJson({geometryType:r.getJsonType(a),geometry:a.toJson()}),reshaper:k.toJson(h.toJson())});var c=this._reshapeHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/reshape",content:a,callbackParamName:"callback",
load:function(a,f){c(a,f,g,e,d,b)},error:function(a){f(a,d,b)}});return b},_reshapeHandler:function(a,h,e,d,g,c){try{var f=r.fromJson(a.geometry).setSpatialReference(e);this._successHandler([f],"onReshapeComplete",d,c)}catch(b){this._errorHandler(b,g,c)}},onReshapeComplete:function(){},cut:function(a,h,e,d){var g=a[0].spatialReference,c=s.map(a,function(a){return a.toJson()});a=m.mixin({},this._url.query,{f:"json",sr:k.toJson(g.toJson()),target:k.toJson({geometryType:r.getJsonType(a[0]),geometries:c}),
cutter:k.toJson(h.toJson())});var f=this._cutHandler,b=this._errorHandler,l=new n(q._dfdCanceller);l._pendingDfd=p({url:this._url.path+"/cut",content:a,callbackParamName:"callback",load:function(a,b){f(a,b,g,e,d,l)},error:function(a){b(a,d,l)}});return l},_cutHandler:function(a,h,e,d,g,c){try{var f=a.geometries,b={};b.cutIndexes=a.cutIndexes;b.geometries=[];s.forEach(f,function(a){b.geometries.push(r.fromJson(a).setSpatialReference(e))});this._successHandler([b],"onCutComplete",d,c)}catch(l){this._errorHandler(l,
g,c)}},onCutComplete:function(){},intersect:function(a,h,e,d){var g=a[0].spatialReference;a=m.mixin({},this._url.query,{f:"json",sr:k.toJson(g.toJson()),geometries:k.toJson(this._encodeGeometries(a)),geometry:k.toJson({geometryType:r.getJsonType(h),geometry:h.toJson()})});var c=this._intersectHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/intersect",content:a,callbackParamName:"callback",load:function(a,f){c(a,f,g,e,d,b)},error:function(a){f(a,d,b)}});
return b},_intersectHandler:function(a,h,e,d,g,c){try{var f=[];s.forEach(a.geometries,function(a){f.push(r.fromJson(a).setSpatialReference(e))});this._successHandler([f],"onIntersectComplete",d,c)}catch(b){this._errorHandler(b,g,c)}},onIntersectComplete:function(){},difference:function(a,h,e,d){var g=a[0].spatialReference;a=m.mixin({},this._url.query,{f:"json",sr:k.toJson(g.toJson()),geometries:k.toJson(this._encodeGeometries(a)),geometry:k.toJson({geometryType:r.getJsonType(h),geometry:h.toJson()})});
var c=this._differenceHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/difference",content:a,callbackParamName:"callback",load:function(a,f){c(a,f,g,e,d,b)},error:function(a){f(a,d,b)}});return b},_differenceHandler:function(a,h,e,d,g,c){try{var f=[];s.forEach(a.geometries,function(a){f.push(r.fromJson(a).setSpatialReference(e))});this._successHandler([f],"onDifferenceComplete",d,c)}catch(b){this._errorHandler(b,g,c)}},onDifferenceComplete:function(){},buffer:function(a,
h,e){var d=m.mixin({},this._url.query,{f:"json"},a.toJson()),g=a.outSpatialReference||a.geometries[0].spatialReference,c=this._bufferHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/buffer",content:d,callbackParamName:"callback",load:function(a,f){c(a,f,g,h,e,b)},error:function(a){f(a,e,b)}});return b},_bufferHandler:function(a,h,e,d,g,c){try{var f=a.geometries;a=[];var b,l=f.length;for(b=0;b<l;b++)a[b]=new v({spatialReference:e,rings:f[b].rings});this._successHandler([a],
"onBufferComplete",d,c)}catch(k){this._errorHandler(k,g,c)}},onBufferComplete:function(){},areasAndLengths:function(a,h,e){a=m.mixin({},this._url.query,{f:"json"},a.toJson());var d=this._areasAndLengthsHandler,g=this._errorHandler,c=new n(q._dfdCanceller);c._pendingDfd=p({url:this._url.path+"/areasAndLengths",content:a,callbackParamName:"callback",load:function(a,b){d(a,b,h,e,c)},error:function(a){g(a,e,c)}});return c},_areasAndLengthsHandler:function(a,h,e,d,g){try{this._successHandler([a],"onAreasAndLengthsComplete",
e,g)}catch(c){this._errorHandler(c,d,g)}},onAreasAndLengthsComplete:function(){},lengths:function(a,h,e){a=m.mixin({},this._url.query,{f:"json"},a.toJson());var d=this._lengthsHandler,g=this._errorHandler,c=new n(q._dfdCanceller);c._pendingDfd=p({url:this._url.path+"/lengths",content:a,callbackParamName:"callback",load:function(a,b){d(a,b,h,e,c)},error:function(a){g(a,e,c)}});return c},_lengthsHandler:function(a,h,e,d,g){try{this._successHandler([a],"onLengthsComplete",e,g)}catch(c){this._errorHandler(c,
d,g)}},onLengthsComplete:function(){},labelPoints:function(a,h,e){var d=s.map(a,function(a){return a.toJson()}),g=a[0].spatialReference,d=m.mixin({},this._url.query,{f:"json",sr:g.wkid?g.wkid:k.toJson(g.toJson()),polygons:k.toJson(d)}),c=this._labelPointsHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/labelPoints",content:d,callbackParamName:"callback",load:function(f,d){c(f,d,a,g,h,e,b)},error:function(a){f(a,e,b)}});return b},_labelPointsHandler:function(a,
h,e,d,g,c,f){try{var b=[];s.forEach(a.labelPoints,function(a){b.push(r.fromJson(a).setSpatialReference(d))});this._successHandler([b],"onLabelPointsComplete",g,f)}catch(l){this._errorHandler(l,c,f)}},onLabelPointsComplete:function(){},relation:function(a,h,e){a=m.mixin({},this._url.query,{f:"json"},a.toJson());var d=this._relationHandler,g=this._errorHandler,c=new n(q._dfdCanceller);c._pendingDfd=p({url:this._url.path+"/relation",content:a,callbackParamName:"callback",load:function(a,b){d(a,b,h,e,
c)},error:function(a){g(a,e,c)}});return c},_relationHandler:function(a,h,e,d,g){try{this._successHandler([a.relations],"onRelationComplete",e,g)}catch(c){this._errorHandler(c,d,g)}},onRelationComplete:function(){},trimExtend:function(a,h,e){var d=m.mixin({},this._url.query,{f:"json"},a.toJson()),g=a.sr,c=this._trimExtendHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/trimExtend",content:d,callbackParamName:"callback",load:function(a,d){c(a,d,g,h,e,b)},
error:function(a){f(a,e,b)}});return b},_trimExtendHandler:function(a,h,e,d,g,c){try{var f=a.geometries;a=[];var b,l=f.length;for(b=0;b<l;b++)a[b]=new x({spatialReference:e,paths:f[b].paths});this._successHandler([a],"onTrimExtendComplete",d,c)}catch(k){this._errorHandler(k,g,c)}},onTrimExtendComplete:function(){},densify:function(a,h,e){var d=m.mixin({},this._url.query,{f:"json"},a.toJson()),g=a.geometries[0].spatialReference,c=this._densifyHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=
p({url:this._url.path+"/densify",content:d,callbackParamName:"callback",load:function(a,d){c(a,d,g,h,e,b)},error:function(a){f(a,e,b)}});return b},_densifyHandler:function(a,h,e,d,g,c){try{var f=[];s.forEach(a.geometries,function(a){f.push(r.fromJson(a).setSpatialReference(e))});this._successHandler([f],"onDensifyComplete",d,c)}catch(b){this._errorHandler(b,g,c)}},onDensifyComplete:function(){},generalize:function(a,h,e){var d=m.mixin({},this._url.query,{f:"json"},a.toJson()),g=a.geometries[0].spatialReference,
c=this._generalizeHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/generalize",content:d,callbackParamName:"callback",load:function(a,d){c(a,d,g,h,e,b)},error:function(a){f(a,e,b)}});return b},_generalizeHandler:function(a,h,e,d,g,c){try{var f=[];s.forEach(a.geometries,function(a){f.push(r.fromJson(a).setSpatialReference(e))});this._successHandler([f],"onGeneralizeComplete",d,c)}catch(b){this._errorHandler(b,g,c)}},onGeneralizeComplete:function(){},offset:function(a,
h,e){var d=m.mixin({},this._url.query,{f:"json"},a.toJson()),g=a.geometries[0].spatialReference,c=this._offsetHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/offset",content:d,callbackParamName:"callback",load:function(a,d){c(a,d,g,h,e,b)},error:function(a){f(a,e,b)}});return b},_offsetHandler:function(a,h,e,d,g,c){try{var f=[];s.forEach(a.geometries,function(a){f.push(r.fromJson(a).setSpatialReference(e))});this._successHandler([f],"onOffsetComplete",d,
c)}catch(b){this._errorHandler(b,g,c)}},onOffsetComplete:function(){},distance:function(a,h,e){var d=m.mixin({},this._url.query,{f:"json"},a.toJson()),g=a.geometry1.spatialReference,c=this._distanceHandler,f=this._errorHandler,b=new n(q._dfdCanceller);b._pendingDfd=p({url:this._url.path+"/distance",content:d,callbackParamName:"callback",load:function(a,d){c(a,d,g,h,e,b)},error:function(a){f(a,e,b)}});return b},_distanceHandler:function(a,h,e,d,g,c){try{a=a&&a.distance,this._successHandler([a],"onDistanceComplete",
d,c)}catch(f){this._errorHandler(f,g,c)}},onDistanceComplete:function(){}});m.mixin(u,{UNIT_METER:9001,UNIT_GERMAN_METER:9031,UNIT_FOOT:9002,UNIT_SURVEY_FOOT:9003,UNIT_CLARKE_FOOT:9005,UNIT_FATHOM:9014,UNIT_NAUTICAL_MILE:9030,UNIT_SURVEY_CHAIN:9033,UNIT_SURVEY_LINK:9034,UNIT_SURVEY_MILE:9035,UNIT_KILOMETER:9036,UNIT_CLARKE_YARD:9037,UNIT_CLARKE_CHAIN:9038,UNIT_CLARKE_LINK:9039,UNIT_SEARS_YARD:9040,UNIT_SEARS_FOOT:9041,UNIT_SEARS_CHAIN:9042,UNIT_SEARS_LINK:9043,UNIT_BENOIT_1895A_YARD:9050,UNIT_BENOIT_1895A_FOOT:9051,
UNIT_BENOIT_1895A_CHAIN:9052,UNIT_BENOIT_1895A_LINK:9053,UNIT_BENOIT_1895B_YARD:9060,UNIT_BENOIT_1895B_FOOT:9061,UNIT_BENOIT_1895B_CHAIN:9062,UNIT_BENOIT_1895B_LINK:9063,UNIT_INDIAN_FOOT:9080,UNIT_INDIAN_1937_FOOT:9081,UNIT_INDIAN_1962_FOOT:9082,UNIT_INDIAN_1975_FOOT:9083,UNIT_INDIAN_YARD:9084,UNIT_INDIAN_1937_YARD:9085,UNIT_INDIAN_1962_YARD:9086,UNIT_INDIAN_1975_YARD:9087,UNIT_FOOT_1865:9070,UNIT_RADIAN:9101,UNIT_DEGREE:9102,UNIT_ARCMINUTE:9103,UNIT_ARCSECOND:9104,UNIT_GRAD:9105,UNIT_GON:9106,UNIT_MICRORADIAN:9109,
UNIT_ARCMINUTE_CENTESIMAL:9112,UNIT_ARCSECOND_CENTESIMAL:9113,UNIT_MIL6400:9114,UNIT_BRITISH_1936_FOOT:9095,UNIT_GOLDCOAST_FOOT:9094,UNIT_INTERNATIONAL_CHAIN:109003,UNIT_INTERNATIONAL_LINK:109004,UNIT_INTERNATIONAL_YARD:109001,UNIT_STATUTE_MILE:9093,UNIT_SURVEY_YARD:109002,UNIT_50KILOMETER_LENGTH:109030,UNIT_150KILOMETER_LENGTH:109031,UNIT_DECIMETER:109005,UNIT_CENTIMETER:109006,UNIT_MILLIMETER:109007,UNIT_INTERNATIONAL_INCH:109008,UNIT_US_SURVEY_INCH:109009,UNIT_INTERNATIONAL_ROD:109010,UNIT_US_SURVEY_ROD:109011,
UNIT_US_NAUTICAL_MILE:109012,UNIT_UK_NAUTICAL_MILE:109013,UNIT_SQUARE_INCHES:"esriSquareInches",UNIT_SQUARE_FEET:"esriSquareFeet",UNIT_SQUARE_YARDS:"esriSquareYards",UNIT_ACRES:"esriAcres",UNIT_SQUARE_MILES:"esriSquareMiles",UNIT_SQUARE_MILLIMETERS:"esriSquareMillimeters",UNIT_SQUARE_CENTIMETERS:"esriSquareCentimeters",UNIT_SQUARE_DECIMETERS:"esriSquareDecimeters",UNIT_SQUARE_METERS:"esriSquareMeters",UNIT_ARES:"esriAres",UNIT_HECTARES:"esriHectares",UNIT_SQUARE_KILOMETERS:"esriSquareKilometers"});
return u});