//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Deferred","dojo/_base/json","dojo/has","dojo/io-query","esri/kernel","esri/request","esri/deferredUtils","esri/geometry/normalizeUtils","esri/tasks/Task","esri/tasks/FeatureSet","esri/tasks/JobInfo","esri/tasks/GPMessage","esri/tasks/LinearUnit","esri/tasks/DataFile","esri/tasks/RasterData","esri/tasks/Date","esri/tasks/ParameterValue","esri/tasks/GPResultImageLayer","esri/layers/MapImage"],function(p,h,s,q,m,G,t,H,l,r,u,v,w,n,x,y,z,A,B,C,D,E){p=p(v,{declaredClass:"esri.tasks.Geoprocessor",
_eventMap:{"execute-complete":["results","messages"],"get-result-data-complete":["result"],"get-result-image-complete":["mapImage"],"get-result-image-layer-complete":["layer"],"job-cancel":["jobInfo"],"job-complete":["jobInfo"],"status-update":["jobInfo"]},constructor:function(a){this._jobUpdateHandler=h.hitch(this,this._jobUpdateHandler);this._getJobStatus=h.hitch(this,this._getJobStatus);this._getResultDataHandler=h.hitch(this,this._getResultDataHandler);this._getResultImageHandler=h.hitch(this,
this._getResultImageHandler);this._executeHandler=h.hitch(this,this._executeHandler);this._updateTimers=[];this.registerConnectEvents()},updateDelay:1E3,processSpatialReference:null,outputSpatialReference:null,outSpatialReference:null,setUpdateDelay:function(a){this.updateDelay=a},setProcessSpatialReference:function(a){this.processSpatialReference=a},setOutputSpatialReference:function(a){this._setOutSR(a)},setOutSpatialReference:function(a){this._setOutSR(a)},__msigns:[{n:"execute",c:3,a:[{i:0,p:["*"]}],
e:2,f:1},{n:"submitJob",c:4,a:[{i:0,p:["*"]}],e:3}],_setOutSR:function(a){this.outSpatialReference=this.outputSpatialReference=a},_getOutSR:function(){return this.outSpatialReference||this.outputSpatialReference},_gpEncode:function(a,d,b){for(var e in a){var c=a[e];h.isArray(c)?a[e]=m.toJson(s.map(c,function(a){return this._gpEncode({item:a},!0).item},this)):c instanceof Date&&(a[e]=c.getTime())}return this._encode(a,d,b)},_decode:function(a){var d=a.dataType,b=new C(a);if(-1!==s.indexOf(["GPBoolean",
"GPDouble","GPLong","GPString"],d))return b;if("GPLinearUnit"===d)b.value=new y(b.value);else if("GPFeatureRecordSetLayer"===d||"GPRecordSet"===d)b.value=new w(b.value);else if("GPDataFile"===d)b.value=new z(b.value);else if("GPDate"===d)a=b.value,h.isString(a)?b.value=new B({date:a}):b.value=new Date(a);else if("GPRasterData"===d||"GPRasterDataLayer"===d)a=a.value.mapImage,b.value=a?new E(a):new A(b.value);else if(-1!==d.indexOf("GPMultiValue:")){var e=d.split(":")[1];a=b.value;b.value=s.map(a,function(a){return this._decode({paramName:"_name",
dataType:e,value:a}).value},this)}else console.log(this.declaredClass+" : GP Data type not handled. : "+b.dataType),b=null;return b},submitJob:function(a,d,b,e,c){var g=this._getOutSR(),f=c.assembly;a=this._gpEncode(h.mixin({},this._url.query,{f:"json","env:outSR":g?g.wkid||m.toJson(g.toJson()):null,"env:processSR":this.processSpatialReference?this.processSpatialReference.wkid||m.toJson(this.processSpatialReference.toJson()):null},a),null,f&&f[0]);var k=this._jobUpdateHandler,F=this._errorHandler;
return l({url:this._url.path+"/submitJob",content:a,callbackParamName:"callback",load:function(a,f){k(a,f,!1,d,b,c.dfd)},error:function(a){F(a,e,c.dfd)}})},_jobUpdateHandler:function(a,d,b,e,c,g){var f=a.jobId;d=new n(a);this._successHandler([d],"onStatusUpdate",c,b&&g);if(!b)switch(clearTimeout(this._updateTimers[f]),this._updateTimers[f]=null,g&&g.progress(d),a.jobStatus){case n.STATUS_SUBMITTED:case n.STATUS_EXECUTING:case n.STATUS_WAITING:case n.STATUS_NEW:var k=this._getJobStatus;this._updateTimers[f]=
setTimeout(function(){k(f,b,e,c,g)},this.updateDelay);break;default:this._successHandler([d],"onJobComplete",e,g)}},_getJobStatus:function(a,d,b,e,c){var g=this._jobUpdateHandler;l({url:this._url.path+"/jobs/"+a,content:h.mixin({},this._url.query,{f:"json"}),callbackParamName:"callback",load:function(a,k){g(a,k,d,b,e,c)},error:this._errorHandler})},_getResultDataHandler:function(a,d,b,e,c){try{var g=this._decode(a);this._successHandler([g],"onGetResultDataComplete",b,c)}catch(f){this._errorHandler(f,
e,c)}},getResultData:function(a,d,b,e){var c=this._getResultDataHandler,g=this._errorHandler,f=new q(r._dfdCanceller);f._pendingDfd=l({url:this._url.path+"/jobs/"+a+"/results/"+d,content:h.mixin({},this._url.query,{f:"json",returnType:"data"}),callbackParamName:"callback",load:function(a,d){c(a,d,b,e,f)},error:function(a){g(a,e,f)}});return f},checkJobStatus:function(a,d,b){var e=this._jobUpdateHandler,c=this._errorHandler,g=new q(r._dfdCanceller);g._pendingDfd=l({url:this._url.path+"/jobs/"+a,content:h.mixin({},
this._url.query,{f:"json"}),callbackParamName:"callback",load:function(a,b){e(a,b,!0,null,d,g)},error:function(a){c(a,b,g)}});return g},cancelJob:function(a,d,b){var e=this._errorHandler,c=new q(r._dfdCanceller);c._pendingDfd=l({url:this._url.path+"/jobs/"+a+"/cancel",content:h.mixin({},this._url.query,{f:"json"}),callbackParamName:"callback",load:h.hitch(this,function(a,b){this._successHandler([a],"onJobCancel",d,c)}),error:function(a){e(a,b,c)}});return c},execute:function(a,d,b,e){var c=this._getOutSR(),
g=e.assembly;a=this._gpEncode(h.mixin({},this._url.query,{f:"json","env:outSR":c?c.wkid||m.toJson(c.toJson()):null,"env:processSR":this.processSpatialReference?this.processSpatialReference.wkid||m.toJson(this.processSpatialReference.toJson()):null},a),null,g&&g[0]);var f=this._executeHandler,k=this._errorHandler;return l({url:this._url.path+"/execute",content:a,callbackParamName:"callback",load:function(a,c){f(a,c,d,b,e.dfd)},error:function(a){k(a,b,e.dfd)}})},_executeHandler:function(a,d,b,e,c){try{var g=
a.results,f,k,h=a.messages;f=0;for(k=g.length;f<k;f++)g[f]=this._decode(g[f]);f=0;for(k=h.length;f<k;f++)h[f]=new x(h[f]);this._successHandler([g,h],"onExecuteComplete",b,c)}catch(l){this._errorHandler(l,e,c)}},_getResultImageHandler:function(a,d,b,e,c){try{var g=this._decode(a);this._successHandler([g],"onGetResultImageComplete",b,c)}catch(f){this._errorHandler(f,e,c)}},getResultImage:function(a,d,b,e,c){var g=this._getResultImageHandler,f=this._errorHandler;b=this._gpEncode(h.mixin({},this._url.query,
{f:"json"},b.toJson()));var k=new q(r._dfdCanceller);k._pendingDfd=l({url:this._url.path+"/jobs/"+a+"/results/"+d,content:b,callbackParamName:"callback",load:function(a,b){g(a,b,e,c,k)},error:function(a){f(a,c,k)}});return k},cancelJobStatusUpdates:function(a){clearTimeout(this._updateTimers[a]);this._updateTimers[a]=null},getResultImageLayer:function(a,d,b,e){a=this._url.path+"/jobs/"+a+"/results/"+d;this._url.query&&(a+="?"+t.objectToQuery(this._url.query));b=new D(a,{imageParameters:b},!0);this.onGetResultImageLayerComplete(b);
e&&e(b);return b},onStatusUpdate:function(){},onJobComplete:function(){},onExecuteComplete:function(){},onGetResultDataComplete:function(){},onGetResultImageComplete:function(){},onGetResultImageLayerComplete:function(){},onJobCancel:function(){}});u._createWrappers(p);return p});