//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/json","dojo/_base/Deferred","dojo/has","esri/kernel","esri/lang","esri/deferredUtils","esri/tasks/Task","esri/renderers/SimpleRenderer","esri/geometry/scaleUtils","esri/tasks/Geoprocessor","esri/tasks/PrintTemplate","esri/symbols/PictureMarkerSymbol","dojo/dom-construct","dojox/gfx/_base","dojox/gfx/canvas","require","require"],function(w,h,m,r,x,y,G,s,z,A,B,C,D,E,H,F,t,u){return w(A,{declaredClass:"esri.tasks.PrintTask",constructor:function(b,f){this.url=
b;this.printGp=new D(this.url);this._handler=h.hitch(this,this._handler);f&&f.async&&(this.async=f.async)},_handler:function(b,f,a,c,d){try{var g;this.async?"esriJobSucceeded"===b.jobStatus&&this.printGp.getResultData(b.jobId,"Output_File",h.hitch(this,function(b){g=b.value;this._successHandler([g],"onComplete",a,d)})):(g=b[0].value,this._successHandler([g],"onComplete",a,d))}catch(e){this._errorHandler(e,c,d)}},execute:function(b,f,a){var c=this._handler,d=this._errorHandler,g=b.template||new E,
e=g.exportOptions,l;e&&(l={outputSize:[e.width,e.height],dpi:e.dpi});this._preserveScale=!1===g.preserveScale?!1:!0;var e=g.layoutOptions,k,v=[];if(e){this.legendAll=!1;e.legendLayers?m.forEach(e.legendLayers,function(a,b){var d={};d.id=a.layerId;a.subLayerIds&&(d.subLayerIds=a.subLayerIds);v.push(d)}):this.legendAll=!0;var n,p;if("Miles"===e.scalebarUnit||"Kilometers"===e.scalebarUnit)n="Kilometers",p="Miles";else if("Meters"===e.scalebarUnit||"Feet"===e.scalebarUnit)n="Meters",p="Feet";k={Miles:"mi",
Kilometers:"km",Yards:"yd",Feet:"ft",Meters:"m"};k={titleText:e.titleText,authorText:e.authorText,copyrightText:e.copyrightText,customTextElements:e.customTextElements,scaleBarOptions:{metricUnit:n,metricLabel:k[n],nonMetricUnit:p,nonMetricLabel:k[p]},legendOptions:{operationalLayers:v}}}n=this._getPrintDefinition(b.map);b.outSpatialReference&&(n.mapOptions.spatialReference=b.outSpatialReference.toJson());b.template&&s.isDefined(b.template.showAttribution)&&(n.mapOptions.showAttribution=b.template.showAttribution);
h.mixin(n,{exportOptions:l,layoutOptions:k});this.allLayerslegend&&h.mixin(n.layoutOptions,{legendOptions:{operationalLayers:this.allLayerslegend}});g={Web_Map_as_JSON:r.toJson(s.fixJson(n)),Format:g.format,Layout_Template:g.layout};b.extraParameters&&(g=h.mixin(g,b.extraParameters));var q=new x(z._dfdCanceller);b=function(b,d){c(b,d,f,a,q)};l=function(b){d(b,a,q)};q._pendingDfd=this.async?this.printGp.submitJob(g,b,null,l):this.printGp.execute(g,b,l);return q},onComplete:function(){},_multipointLayer:function(){this.layerDefinition=
{name:"multipointLayer",geometryType:"esriGeometryMultipoint",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryMultipoint",features:[]}},_polygonLayer:function(){this.layerDefinition={name:"polygonLayer",geometryType:"esriGeometryPolygon",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPolygon",features:[]}},_pointLayer:function(){this.layerDefinition={name:"pointLayer",geometryType:"esriGeometryPoint",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPoint",
features:[]}},_polylineLayer:function(){this.layerDefinition={name:"polylineLayer",geometryType:"esriGeometryPolyline",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPolyline",features:[]}},_convertSvgSymbol:function(b){if(!(8>=y("ie"))&&b.path){this._canvasHolder||(this._canvasHolder=F.create("div"),this._canSurface=u.createSurface(this._canvasHolder,200,200));var f=this._canSurface.createObject(u.Path,b.path).setFill(b.color).setStroke(b.outline);"pendingRender"in this._canSurface&&
this._canSurface._render(!0);var a=this._canSurface.rawNode.getContext("2d"),c=Math.ceil(f.getBoundingBox().width+f.getBoundingBox().x),d=Math.ceil(f.getBoundingBox().height+f.getBoundingBox().y),g=a.getImageData(f.getBoundingBox().x,f.getBoundingBox().y,c,d);a.canvas.width=c;a.canvas.height=d;a.putImageData(g,0,0);a=a.canvas.toDataURL("image/png");return{type:"esriPMS",imageData:a.substr(22,a.length),angle:-b.angle,contentType:"image/png",height:b.size?b.size:d-f.getBoundingBox().y,width:b.size?
b.size:c-f.getBoundingBox().x,xoffset:b.xoffset,yoffset:b.yoffset}}},_convertSvgRenderer:function(b){"simple"===b.type&&b.symbol&&b.symbol.path?b.symbol=this._convertSvgSymbol(b.symbol):"uniqueValue"===b.type?(b.defaultSymbol&&b.defaultSymbol.path&&(b.defaultSymbol=this._convertSvgSymbol(b.defaultSymbol)),b.uniqueValueInfos&&m.forEach(b.uniqueValueInfos,function(b){b.symbol.path&&(b.symbol=this._convertSvgSymbol(b.symbol))},this)):"classBreaks"===b.type&&(b.defaultSymbol&&b.defaultSymbol.path&&(b.defaultSymbol=
this._convertSvgSymbol(b.defaultSymbol)),b.classBreakInfos&&m.forEach(b.classBreakInfos,function(b){b.symbol.path&&(b.symbol=this._convertSvgSymbol(b.symbol))},this))},_createFeatureCollection:function(b,f){var a=new this._polygonLayer,c=new this._polylineLayer,d=new this._pointLayer,g=new this._multipointLayer;"esri.layers.FeatureLayer"===b.declaredClass&&(a.layerDefinition.name=c.layerDefinition.name=d.layerDefinition.name=g.layerDefinition.name=b.name||b.id);b.renderer&&!h.isFunction(b.renderer.attributeField)?
(a.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),c.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),d.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),g.layerDefinition.drawingInfo.renderer=b.renderer.toJson()):(delete a.layerDefinition.drawingInfo,delete c.layerDefinition.drawingInfo,delete d.layerDefinition.drawingInfo,delete g.layerDefinition.drawingInfo);b.fields&&(a.layerDefinition.fields=b.fields,c.layerDefinition.fields=b.fields,d.layerDefinition.fields=b.fields,
g.layerDefinition.fields=b.fields);var e,l;for(l=0;l<b.graphics.length;l++){var k=b.graphics[l];if(!1!==k.visible&&k.geometry){e=k.toJson();e.symbol&&(e.symbol.outline&&e.symbol.outline.color&&e.symbol.outline.color[3])&&(e.symbol.outline.color[3]=255);if(b.renderer&&!e.symbol&&(h.isFunction(b.renderer.attributeField)||b.renderer.proportionalSymbolInfo||"esri.renderer.DotDensityRenderer"===b.renderer.declaredClass||f))if(f=f||b.renderer,e.symbol=f.getSymbol(k)?f.getSymbol(k).toJson():e.symbol,f.proportionalSymbolInfo)if(f.getSize(k))"point"===
k.geometry.type||"multipoint"===k.geometry.type||"polygon"===k.geometry.type?e.symbol.size=t.px2pt(f.getSize(k)):"polyline"===k.geometry.type&&(e.symbol.width=t.px2pt(f.getSize(k)));else continue;e.symbol&&e.symbol.path&&(e.symbol=this._convertSvgSymbol(e.symbol));switch(k.geometry.type){case "polygon":a.featureSet.features.push(e);break;case "polyline":c.featureSet.features.push(e);break;case "point":d.featureSet.features.push(e);break;case "multipoint":g.featureSet.features.push(e)}}}e=[];0<d.featureSet.features.length&&
e.push(d);0<c.featureSet.features.length&&e.push(c);0<a.featureSet.features.length&&e.push(a);0<g.featureSet.features.length&&e.push(g);m.forEach(e,function(a){a.layerDefinition.drawingInfo&&a.layerDefinition.drawingInfo.renderer&&this._convertSvgRenderer(a.layerDefinition.drawingInfo.renderer)},this);return{id:b.id,opacity:b.opacity,minScale:b.minScale||0,maxScale:b.maxScale||0,featureCollection:{layers:e}}},_getPrintDefinition:function(b){var f={operationalLayers:this._createOperationalLayers(b)},
a=b.extent,c=b.spatialReference;b.spatialReference._isWrappable()&&(a=a._normalize(!0),c=a.spatialReference);a={mapOptions:{showAttribution:b.showAttribution,extent:a.toJson(),spatialReference:c.toJson()}};this._preserveScale&&h.mixin(a.mapOptions,{scale:C.getScale(b)});b.timeExtent&&h.mixin(a.mapOptions,{time:[b.timeExtent.startTime.getTime(),b.timeExtent.endTime.getTime()]});b={};h.mixin(b,a,f);return b},_createOperationalLayers:function(b){var f,a,c,d,g=[],e=[];this.allLayerslegend=this.legendAll?
[]:null;for(f=0;f<b.layerIds.length;f++)if(a=b.getLayer(b.layerIds[f]),a.loaded&&a.visible&&-1===m.indexOf(g,a.id))switch(a.credential&&-1===a.url.indexOf("token\x3d")&&(a.url+="?token\x3d"+a.credential.token),c=a.declaredClass,d={id:a.id,title:a.id,opacity:a.opacity,minScale:a.minScale||0,maxScale:a.maxScale||0},c){case "esri.layers.ArcGISDynamicMapServiceLayer":var l=[];a._params.dynamicLayers?(c=r.fromJson(a._params.dynamicLayers),m.forEach(c,function(a,b){l.push({id:a.id,layerDefinition:a})})):
m.forEach(a.layerInfos,function(b,d){var c={id:b.id,layerDefinition:{definitionExpression:null,layerTimeOptions:null}};a.layerDefinitions&&a.layerDefinitions[b.id]&&(c.layerDefinition.definitionExpression=a.layerDefinitions[b.id]);a.layerTimeOptions&&a.layerTimeOptions[b.id]&&(c.layerDefinition.layerTimeOptions=a.layerTimeOptions[b.id]);(c.layerDefinition.definitionExpression||c.layerDefinition.layerTimeOptions)&&l.push(c)});d=h.mixin(d,{url:a.url,visibleLayers:a._params.layers?a.visibleLayers:null,
layers:l});e.push(d);this.allLayerslegend&&this.allLayerslegend.push({id:a.id,subLayerIds:a.visibleLayers});break;case "esri.layers.ArcGISImageServiceLayer":d=h.mixin(d,{url:a.url,bandIds:a.bandIds,compressionQuality:a.compressionQuality,format:a.format,interpolation:a.interpolation});a.mosaicRule&&h.mixin(d,{mosaicRule:a.mosaicRule.toJson()});a.renderingRule&&h.mixin(d,{renderingRule:a.renderingRule.toJson()});e.push(d);this.allLayerslegend&&this.allLayerslegend.push({id:a.id});break;case "esri.layers.WMSLayer":d=
h.mixin(d,{url:a.url,title:a.title,type:"wms",version:a.version,transparentBackground:a.imageTransparency,visibleLayers:a.visibleLayers});e.push(d);this.allLayerslegend&&this.allLayerslegend.push({id:a.id,subLayerIds:a.visibleLayers});break;case "esri.virtualearth.VETiledLayer":c=a.mapStyle;"aerialWithLabels"===c&&(c="Hybrid");d=h.mixin(d,{visibility:a.visible,type:"BingMaps"+c,culture:a.culture,key:a.bingMapsKey});e.push(d);break;case "esri.layers.OpenStreetMapLayer":d=h.mixin(d,{type:"OpenStreetMap",
url:a.tileServers[0]});e.push(d);break;case "esri.layers.WMTSLayer":d=h.mixin(d,{url:a.url,type:"wmts",layer:a.layerInfos[0].identifier,style:a.layerInfos[0].style,format:a.layerInfos[0].format,tileMatrixSet:a.layerInfos[0].tileMatrixSet});e.push(d);break;case "esri.layers.MapImageLayer":c=a.getImages();m.forEach(c,function(b,c){b.href&&(d={id:a.id+"_image"+c,type:"image",title:a.id,minScale:a.minScale||0,maxScale:a.maxScale||0,opacity:a.opacity,extent:b.extent.toJson(),url:b.href},e.push(d))});break;
case "esri.layers.WebTiledLayer":c=a.url.replace(/\$\{/g,"{");d=h.mixin(d,{type:"WebTiledLayer",urlTemplate:c,credits:a.copyright});a.subDomains&&0<a.subDomains.length&&(d.subDomains=a.subDomains);e.push(d);break;default:if(a.getTileUrl||a.getImageUrl)d=h.mixin(d,{url:a.url}),e.push(d)}for(f=0;f<b.graphicsLayerIds.length;f++)if(a=b.getLayer(b.graphicsLayerIds[f]),a.loaded&&a.visible&&-1===m.indexOf(g,a.id))switch(c=a.declaredClass,c){case "esri.layers.FeatureLayer":case "esri.layers.LabelLayer":c=
null;a.url&&a.renderer&&("esri.renderer.ScaleDependentRenderer"===a.renderer.declaredClass?"scale"===a.renderer.rangeType?c=a.renderer.getRendererInfoByScale(b.getScale())&&a.renderer.getRendererInfoByScale(b.getScale()).renderer:"zoom"===a.renderer.rangeType&&(c=a.renderer.getRendererInfoByZoom(b.getZoom())&&a.renderer.getRendererInfoByZoom(b.getZoom()).renderer):c=a.renderer);if(c&&("esri.renderer.SimpleRenderer"===c.declaredClass||h.isString(c.attributeField)&&a._getField(c.attributeField,!0))&&
!c.proportionalSymbolInfo&&"esri.renderer.DotDensityRenderer"!==c.declaredClass)if(a.credential&&-1===a.url.indexOf("token\x3d")&&(a.url+="?token\x3d"+a.credential.token),d={id:a.id,url:a.url,title:a.id,opacity:a.opacity,minScale:a.minScale||0,maxScale:a.maxScale||0,layerDefinition:{drawingInfo:{renderer:c.toJson()}}},this._convertSvgRenderer(d.layerDefinition.drawingInfo.renderer),a._params.source&&(c=a._params.source.toJson(),h.mixin(d.layerDefinition,{source:c})),a.getDefinitionExpression()&&h.mixin(d.layerDefinition,
{definitionExpression:a.getDefinitionExpression()}),2!==a.mode)0<a.getSelectedFeatures().length&&(c=m.map(a.getSelectedFeatures(),function(b){return b.attributes[a.objectIdField]}),0<c.length&&a.getSelectionSymbol()&&h.mixin(d,{selectionObjectIds:c,selectionSymbol:a.getSelectionSymbol().toJson()}));else{c=m.map(a.getSelectedFeatures(),function(b){return b.attributes[a.objectIdField]});if(0===c.length||!a._params.drawMode)break;h.mixin(d.layerDefinition,{objectIds:c});c=null;a.getSelectionSymbol()&&
(c=new B(a.getSelectionSymbol()));h.mixin(d.layerDefinition.drawingInfo,{renderer:c&&c.toJson()})}else d=c&&(c.proportionalSymbolInfo||"esri.renderer.DotDensityRenderer"===c.declaredClass)?this._createFeatureCollection(a,c):this._createFeatureCollection(a);e.push(d);this.allLayerslegend&&this.allLayerslegend.push({id:a.id});break;case "esri.layers.GraphicsLayer":d=this._createFeatureCollection(a),e.push(d),this.allLayerslegend&&this.allLayerslegend.push({id:a.id})}b.graphics&&0<b.graphics.graphics.length&&
(d=this._createFeatureCollection(b.graphics),e.push(d));return e}})});