//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/connect","dojo/_base/Color","dojo/has","dojo/dom-style","dojox/gfx/Moveable","dojox/gfx/matrix","esri/kernel","esri/lang","esri/geometry/Point","esri/geometry/Polyline","esri/symbols/SimpleMarkerSymbol","esri/geometry/webMercatorUtils","esri/geometry/jsonUtils","esri/graphic"],function(r,l,h,m,x,y,s,t,k,z,u,n,v,A,p,w,q){return r(null,{declaredClass:"esri.toolbars._Box",constructor:function(d,b,a,c,e,f,g){this._graphic=d;this._map=b;this._toolbar=
a;this._scale=c;this._rotate=e;this._defaultEventArgs={};this._scaleEvent="Scale";this._rotateEvent="Rotate";this._uniformScaling=f;d=a._options;this._markerSymbol=d.boxHandleSymbol;this._lineSymbol=d.boxLineSymbol;this._moveStartHandler=l.hitch(this,this._moveStartHandler);this._firstMoveHandler=l.hitch(this,this._firstMoveHandler);this._moveStopHandler=l.hitch(this,this._moveStopHandler);this._moveHandler=l.hitch(this,this._moveHandler);this._isTextPoint=g;this._init()},destroy:function(){this._cleanUp();
this._graphic=this._map=this._toolbar=this._markerSymbol=this._lineSymbol=null},refresh:function(){this._draw()},suspend:function(){h.forEach(this._getAllGraphics(),function(d){d.hide()})},resume:function(){h.forEach(this._getAllGraphics(),function(d){d.show()});this._draw()},_init:function(){this._draw()},_cleanUp:function(){this._connects&&h.forEach(this._connects,m.disconnect);var d=this._toolbar._scratchGL;this._anchors&&h.forEach(this._anchors,function(b){d.remove(b.graphic);(b=b.moveable)&&
b.destroy()});this._box&&d.remove(this._box);this._box=this._anchors=this._connects=null},_draw:function(){if(this._graphic.getDojoShape()){var d=this._map,b=this._toolbar._scratchGL,a=this._getBoxCoords(),c=new v(d.spatialReference),e=l.clone(h.filter(a,function(a,b){return 8!==b&&0===b%2}));e[0]&&e.push([e[0][0],e[0][1]]);c.addPath(e);this._rotate&&c.addPath([a[1],a[8]]);this._box?this._box.setGeometry(c):(this._box=new q(c,this._lineSymbol),b.add(this._box));this._anchors?h.forEach(this._anchors,
function(b,c){this._scale||(c=8);var e=new n(a[c],d.spatialReference);b.graphic.setGeometry(e);var e=b.moveable,h=b.graphic.getDojoShape();h&&(e?h!==e.shape&&(e.destroy(),b.moveable=this._getMoveable(b.graphic,c)):b.moveable=this._getMoveable(b.graphic,c))},this):(this._anchors=[],this._connects=[],h.forEach(a,function(a,c){if(this._scale||!(8>c)){a=new n(a,d.spatialReference);var e=new q(a,this._markerSymbol);this._isTextPoint&&1===c%2&&e.hide();b.add(e);this._anchors.push({graphic:e,moveable:this._getMoveable(e,
c)})}},this))}else this._cleanUp()},_getBoxCoords:function(d){var b=this._map,a,c=[],e,f,g;this._isTextPoint?(a=this._graphic.getNode().getBoundingClientRect(),mapRec=b.__container.getBoundingClientRect(),topLeft=b.toMap({x:a.left,y:a.top}),bottomRight=b.toMap({x:a.right,y:a.bottom}),a=[{x:a.left-mapRec.left,y:a.top-mapRec.top},{x:a.right-mapRec.left,y:a.top-mapRec.top},{x:a.right-mapRec.left,y:a.bottom-mapRec.top},{x:a.left-mapRec.left,y:a.bottom-mapRec.top}]):a=this._getTransformedBoundingBox(this._graphic);
h.forEach(a,function(a,h,k){e=a;(f=k[h+1])||(f=k[0]);g={x:(e.x+f.x)/2,y:(e.y+f.y)/2};d||(e=b.toMap(e),g=b.toMap(g));c.push([e.x,e.y]);c.push([g.x,g.y])});this._rotate&&(a=l.clone(c[1]),a=d?{x:a[0],y:a[1]}:b.toScreen({x:a[0],y:a[1],spatialReference:b.spatialReference}),a.y-=this._toolbar._options.rotateHandleOffset,d||(a=b.toMap(a)),c.push([a.x,a.y]));return c},_getTransformedBoundingBox:function(d){var b=this._map,a=d.geometry.getExtent(),c=d.geometry.spatialReference;d=new n(a.xmin,a.ymax,c);a=new n(a.xmax,
a.ymin,c);d=b.toScreen(d);a=b.toScreen(a);return[{x:d.x,y:d.y},{x:a.x,y:d.y},{x:a.x,y:a.y},{x:d.x,y:a.y}]},_getAllGraphics:function(){var d=[this._box];this._anchors&&h.forEach(this._anchors,function(b){d.push(b.graphic)});return d=h.filter(d,u.isDefined)},_getMoveable:function(d,b){var a=d.getDojoShape();if(a){var c=new t(a);c._index=b;this._connects.push(m.connect(c,"onMoveStart",this._moveStartHandler));this._connects.push(m.connect(c,"onFirstMove",this._firstMoveHandler));this._connects.push(m.connect(c,
"onMoveStop",this._moveStopHandler));c.onMove=this._moveHandler;(a=a.getEventSource())&&s.set(a,"cursor",this._toolbar._cursors["box"+b]);return c}},_moveStartHandler:function(d){this._toolbar["on"+(8===d.host._index?this._rotateEvent:this._scaleEvent)+"Start"](this._graphic)},_firstMoveHandler:function(d){var b=d.host._index,a=this._wrapOffset=d.host.shape._wrapOffsets[0]||0,c=this._graphic.getLayer()._div.getTransform(),e;d=h.map(this._getBoxCoords(!0),function(b){return{x:b[0]+a,y:b[1]}});e=this._isTextPoint?
this._map.toScreen(this._graphic.geometry):{x:d[1].x,y:d[3].y};this._centerCoord=k.multiplyPoint(k.invert(c),e);if(8===b)e=k.multiplyPoint(k.invert(c),d[1]),this._isTextPoint&&(this._centerCoord=this._deNormalizePoint(this._centerCoord,e)),this._startLine=[this._centerCoord,e],this._moveLine=l.clone(this._startLine);else if(e=k.multiplyPoint(k.invert(c),d[b]),c=k.multiplyPoint(k.invert(c),d[(b+4)%8]),this._isTextPoint&&(this._centerCoord=this._deNormalizePoint(this._centerCoord,e)),this._firstMoverToAnchor=
Math.sqrt((e.x-this._centerCoord.x)*(e.x-this._centerCoord.x)+(e.y-this._centerCoord.y)*(e.y-this._centerCoord.y)),this._startBox=c,this._startBox.width=d[4].x-d[0].x,this._startBox.height=d[4].y-d[0].y,this._moveBox=l.clone(this._startBox),this._xfactor=e.x>c.x?1:-1,this._yfactor=e.y>c.y?1:-1,1===b||5===b)this._xfactor=0;else if(3===b||7===b)this._yfactor=0;this._toolbar._beginOperation("BOX");this._toolbar["on"+(8===b?this._rotateEvent:this._scaleEvent)+"FirstMove"](this._graphic)},_moveHandler:function(d,
b){var a=d.host._index,c=this._defaultEventArgs,e,f,g,h;c.angle=0;c.scaleX=1;c.scaleY=1;if(8===a)e=this._startLine,f=this._moveLine,g=f[1],g.x+=b.dx,g.y+=b.dy,g=this._getAngle(e,f),this._isTextPoint&&(g+=this._graphic.symbol.angle),f=k.rotategAt(g,e[0]),this._graphic.getDojoShape().setTransform(f),c.transform=f,c.angle=g,c.around=e[0];else{e=this._startBox;f=this._moveBox;f.width+=b.dx*this._xfactor;f.height+=b.dy*this._yfactor;this._uniformScaling||this._isTextPoint?(e=f.x+this._xfactor*f.width,
f=f.y+this._yfactor*f.height,e=Math.sqrt((e-this._centerCoord.x)*(e-this._centerCoord.x)+(f-this._centerCoord.y)*(f-this._centerCoord.y)),this._scaleRatio=g=h=e/this._firstMoverToAnchor,e=this._centerCoord):(g=f.width/e.width,h=f.height/e.height,e={x:e.x,y:e.y});if(isNaN(g)||Infinity===g||-Infinity===g)g=1;if(isNaN(h)||Infinity===h||-Infinity===h)h=1;f=k.scaleAt(g,h,e);if(this._isTextPoint){var l=k.rotategAt(this._graphic.symbol.angle,e);this._graphic.getDojoShape().setTransform([l,f])}else this._graphic.getDojoShape().setTransform(f);
c.transform=f;c.scaleX=g;c.scaleY=h;c.around=e}this._toolbar["on"+(8===a?this._rotateEvent:this._scaleEvent)](this._graphic,c)},_moveStopHandler:function(d){var b=this._graphic,a=this._toolbar,c=a._geo?p.geographicToWebMercator(b.geometry):b.geometry,e=c.spatialReference,f=b.getDojoShape(),g=f.getTransform(),h=b.getLayer()._div.getTransform();this._isTextPoint?(b=this._graphic.symbol,8===d.host._index?b.angle+=this._getAngle(this._startLine,this._moveLine):b.font.setSize(Math.round(100*b.font.size*
this._scaleRatio)/100),this._graphic.setSymbol(b)):(c=c.toJson(),this._updateSegments(c.paths||c.rings,g,h,e),f.setTransform(null),c=w.fromJson(c),b.setGeometry(a._geo?p.webMercatorToGeographic(c,!0):c));this._draw();this._startLine=this._moveLine=this._startBox=this._moveBox=this._xfactor=this._yfactor=null;a._endOperation("BOX");this._defaultEventArgs.transform=g;a["on"+(8===d.host._index?this._rotateEvent:this._scaleEvent)+"Stop"](this._graphic,this._defaultEventArgs)},_updateSegments:function(d,
b,a,c){var e=this._map,f=this._wrapOffset||0;h.forEach(d,function(d){h.forEach(d,function(d){this._updatePoint(d,c,f,k,e,a,b)},this)},this)},_updatePoint:function(d,b,a,c,e,f,g){b=e.toScreen({x:d[0],y:d[1],spatialReference:b},!0);b.x+=a;b=c.multiplyPoint([f,g,c.invert(f)],b);b.x-=a;a=e.toMap(b);d[0]=a.x;d[1]=a.y},_getAngle:function(d,b){var a=180*Math.atan2(d[0].y-d[1].y,d[0].x-d[1].x)/Math.PI;return 180*Math.atan2(b[0].y-b[1].y,b[0].x-b[1].x)/Math.PI-a},_deNormalizePoint:function(d,b){for(var a=
this._map._getFrameWidth(),c={x:d.x,y:d.y};Math.abs(c.x-b.x)>=a;)c.x=c.x<b.x?c.x+a:c.x-a;var e=Math.abs(c.x-b.x);Math.abs(c.x-b.x+a)<e?c.x+=a:Math.abs(c.x-b.x-a)<e&&(c.x-=a);return c}})});