//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/connect","dojo/_base/array","dojo/_base/Color","dojo/has","esri/kernel","esri/lang","esri/sniff","esri/toolbars/_toolbar","esri/toolbars/_Box","esri/toolbars/_GraphicMover","esri/toolbars/_VertexEditor","esri/toolbars/TextEditor","esri/symbols/SimpleMarkerSymbol","esri/symbols/SimpleLineSymbol","esri/symbols/TextSymbol","esri/graphic"],function(u,l,h,g,f,m,C,t,D,v,w,x,y,z,e,d,A,B){var c=u(v,{declaredClass:"esri.toolbars.Edit",constructor:function(a,b){this._map=a;
this._tool=0;if(this._map.loaded)this._scratchGL=a.graphics;else var k=h.connect(this._map,"onLoad",this,function(){h.disconnect(k);k=null;this._scratchGL=this._map.graphics});var c=m("esri-touch")||m("esri-pointer");this._defaultOptions=l.mixin({vertexSymbol:new e(e.STYLE_CIRCLE,c?20:12,new d(d.STYLE_SOLID,new f([0,0,0,0.5]),1),new f([128,128,128])),ghostVertexSymbol:new e(e.STYLE_CIRCLE,c?18:10,new d(d.STYLE_SOLID,new f([0,0,0,0.5]),1),new f([255,255,255,0.75])),ghostLineSymbol:new d(d.STYLE_DOT,
new f([128,128,128]),2),allowDeleteVertices:!0,allowAddVertices:!0,rotateHandleOffset:c?24:16,boxLineSymbol:new d(d.STYLE_DASH,new f([64,64,64]),1),boxHandleSymbol:new e(e.STYLE_SQUARE,c?16:9,new d(d.STYLE_SOLID,new f([0,0,0,0.5]),1),new f([255,255,255,0.75])),textAnchorSymbol:new e(e.STYLE_CIRCLE,10,null,new f([255,0,0]))},b||{})},activate:function(a,b,k){this.deactivate();this._graphic=b;this._options=l.mixin(l.mixin({},this._defaultOptions),k||{});var d=c.MOVE;k=c.EDIT_VERTICES;var f=c.SCALE,e=
c.ROTATE,g=c.EDIT_TEXT,p=!1,q=!1,m=!1,n=this._map,r=n.spatialReference,s=b.geometry.spatialReference;this._geo=!(!r||!s||r.equals(s)||!(r.isWebMercator()&&4326===s.wkid));this._isTextPoint=this._prepareTextSymbolEditing(b,a);(a&d)===d&&(p=this._enableMove(b));d=(a&f)===f;e=(a&e)===e;if(d||e)m=this._enableBoxEditing(b,d,e);(a&k)===k&&(q=this._enableVertexEditing(b));(a&g)===g&&this._enableTextEditing(b);if(!p&&!q&&!m)throw Error("[esri.toolbars.Edit::activate] Unable to activate the tool. Check if the tool is valid for the given geometry type.");
if(this._tool=a)this._mapPanEndHandle=h.connect(n,"onPanEnd",this,this._mapPanEndHandler),this._mapExtChgHandle=h.connect(n,"onExtentChange",this,this._mapExtentChangeHandler),this.onActivate(this._tool,b);n.snappingManager&&(p||q)&&n.snappingManager._startSelectionLayerQuery()},deactivate:function(){this._isTextPoint=null;var a=this._tool,b=this._graphic;if(a){var c=!!this._modified;this._clear();h.disconnect(this._mapPanEndHandle);h.disconnect(this._mapExtChgHandle);this._graphic=this._geo=this._mapPanEndHandle=
this._mapExtChgHandle=null;this.onDeactivate(a,b,{isModified:c});this._map.snappingManager&&this._map.snappingManager._stopSelectionLayerQuery()}},refresh:function(){this._refreshMoveables(!0)},getCurrentState:function(){return{tool:this._tool,graphic:this._graphic,isModified:!!this._modified}},onActivate:function(a,b){},onDeactivate:function(a,b,c){},onGraphicMoveStart:function(a){},onGraphicFirstMove:function(a){this._modified=!0},onGraphicMove:function(a,b){},onGraphicMoveStop:function(a,b){},
onGraphicClick:function(a,b){},onVertexMoveStart:function(a,b){},onVertexFirstMove:function(a,b){this._modified=!0},onVertexMove:function(a,b,c){},onVertexMoveStop:function(a,b,c){},onVertexAdd:function(a,b){this._modified=!0},onVertexClick:function(a,b){},onVertexMouseOver:function(a,b){},onVertexMouseOut:function(a,b){},onVertexDelete:function(a,b){this._modified=!0},onTextEditStart:function(a,b){},onTextEditEnd:function(a){},onScaleStart:function(a){},onScaleFirstMove:function(a){this._modified=
!0},onScale:function(a,b){},onScaleStop:function(a,b){},onRotateStart:function(a){},onRotateFirstMove:function(a){this._modified=!0},onRotate:function(a,b){},onRotateStop:function(a,b){},_eventMap:{activate:["tool","graphic"],deactivate:["tool","graphic","info"],"graphic-move-start":["graphic"],"graphic-first-move":["graphic"],"graphic-move":["graphic","transform"],"graphic-move-stop":["graphic","transform"],"graphic-click":["graphic","info"],"vertex-move-start":["graphic","vertexinfo"],"vertex-first-move":["graphic",
"vertexinfo"],"vertex-move":["graphic","vertexinfo","transform"],"vertex-move-stop":["graphic","vertexinfo","transform"],"vertex-add":["graphic","vertexinfo"],"vertex-click":["graphic","vertexinfo"],"vertex-mouse-over":["graphic","vertexinfo"],"vertex-mouse-out":["graphic","vertexinfo"],"vertex-delete":["graphic","vertexinfo"],"scale-start":["graphic"],"scale-first-move":["graphic"],scale:["graphic","info"],"scale-stop":["graphic","info"],"rotate-start":["graphic"],"rotate-first-move":["graphic"],
rotate:["graphic","info"],"rotate-stop":["graphic","info"]},_prepareTextSymbolEditing:function(a,b){if("point"===a.geometry.type||"multipoint"===a.geometry.type){var d=a.symbol||a.getLayer()._getSymbol(a);if("textsymbol"===d.type){((b&c.SCALE)===c.SCALE||(b&c.ROTATE)===c.ROTATE||(b&c.EDIT_TEXT)===c.EDIT_TEXT)&&a.setSymbol(new A(d.toJson()));if((b&c.MOVE)===c.MOVE||(b&c.ROTATE)===c.ROTATE||(b&c.SCALE)===c.SCALE)this._textAnchor=new B(a.geometry,this._options.textAnchorSymbol),this._scratchGL.add(this._textAnchor);
return!0}}return!1},_enableMove:function(a){var b=this._map;switch(a.geometry.type){case "point":case "polyline":case "polygon":return this._graphicMover=new x(a,b,this,this._textAnchor),!0}return!1},_enableVertexEditing:function(a){var b=this._map;switch(a.geometry.type){case "multipoint":case "polyline":case "polygon":return this._vertexEditor=y.create(a,b,this),!0}return!1},_enableBoxEditing:function(a,b,c){var d=this._map,e=a.geometry.type;return"polyline"===e||"polygon"===e||this._isTextPoint?
(this._boxEditor=new w(a,d,this,b,c,this._options.uniformScaling,this._isTextPoint),!0):!1},_enableTextEditing:function(a){return this._isTextPoint?(this._textEditor=new z(a,this._map,this),h.connect(this._textEditor,"onEditStart",l.hitch(this,function(){this._textAnchor&&(this._textAnchor.getLayer().remove(this._textAnchor),this._textAnchor=null);this._disableMove();this._disableBoxEditing()})),!0):!1},_disableMove:function(){var a=this._graphicMover;a&&(a.destroy(),this._graphicMover=null)},_disableVertexEditing:function(){var a=
this._vertexEditor;a&&(a.destroy(),this._vertexEditor=null)},_disableBoxEditing:function(){var a=this._boxEditor;a&&(a.destroy(),this._boxEditor=null)},_disableTextEditing:function(){this._textEditor&&(this._textEditor.destroy(),this._textEditor=null)},_clear:function(){this._disableMove();this._disableVertexEditing();this._disableBoxEditing();this._disableTextEditing();this._textAnchor&&(this._textAnchor.getLayer().remove(this._textAnchor),this._textAnchor=null);this._tool=0;this._modified=!1},_mapPanEndHandler:function(){this._refreshMoveables()},
_mapExtentChangeHandler:function(a,b,c){c&&this._refreshMoveables()},_refreshMoveables:function(a){var b=g.filter([this._graphicMover,this._vertexEditor,this._boxEditor],t.isDefined);g.forEach(b,function(b){b.refresh(a)})},_beginOperation:function(a){g.forEach(this._getAffectedTools(a),function(a){a.suspend()})},_endOperation:function(a){g.forEach(this._getAffectedTools(a),function(a){a.resume()})},_getAffectedTools:function(a){var b=[];switch(a){case "MOVE":b=[this._vertexEditor,this._boxEditor];
break;case "VERTICES":b=[this._boxEditor];break;case "BOX":b=[this._vertexEditor]}return b=g.filter(b,t.isDefined)}});l.mixin(c,{MOVE:1,EDIT_VERTICES:2,SCALE:4,ROTATE:8,EDIT_TEXT:16});return c});