//>>built
define(["dojo/_base/array","dojo/_base/config","dojo/_base/Deferred","dojo/_base/lang","dojo/_base/url","dojo/_base/xhr","dojo/io/script","dojo/io/iframe","dojo/dom-construct","dojo/io-query","esri/kernel","esri/config","esri/sniff","esri/lang","esri/urlUtils","esri/deferredUtils"],function(x,I,Q,p,O,z,V,W,R,S,l,X,s,y,q,Y){function J(a){a=new O(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function B(a,d,e,f){var h=!1,n=!1,t;y.isDefined(d)&&(p.isObject(d)?(h=!!d.useProxy,n=!!d.usePost,t=d.crossOrigin):h=!!d);
a=p.mixin({},a);a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));d=a.content;var k=a.url,g=e&&a.form,r=m;t=y.isDefined(t)?t:r.useCors;a.load=function(a){var b;a&&(a.error?(b=p.mixin(Error(),a.error),b.log=I.isDebug):"error"===a.status&&(b=p.mixin(Error(),a),b.log=I.isDebug),b&&!y.isDefined(b.httpCode)&&(b.httpCode=b.code));return b||a};a.error=function(a,b){b&&b.xhr&&b.xhr.abort();a instanceof Error||(a=p.mixin(Error(),a));a.log=I.isDebug;r.errorHandler(a,b);return a};a._token&&(a.content=a.content||
{},a.content.token=a._token);var A=0;d&&k&&(A=S.objectToQuery(d).length+k.length+1);a.timeout=y.isDefined(a.timeout)?a.timeout:r.timeout;a.handleAs=a.handleAs||"json";try{var u,v,w=t&&q.canUseXhr(a.url)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),b=q.hasSameOrigin(a.url,window.location.href)||w,c=n||e||A>r.postLength?!0:!1,T=!b&&-1!==a.handleAs.indexOf("json")&&a.callbackParamName&&!e?!0:!1,C=q.getProxyRule(a.url)||r.alwaysUseProxy||h||(!T||c)&&!b?!0:!1;e&&(!s("esri-file-upload")&&
!C&&w)&&(C=!0);if(C)if(u=q.getProxyUrl(k,t),v=u.path,u._xo&&(w=!0),!c&&v.length+1+A>r.postLength&&(c=!0),a.url=v+"?"+k,c)a.content=p.mixin(u.query||{},d);else{var U=S.objectToQuery(p.mixin(u.query||{},d));U&&(a.url+="?"+U);a.content=null}if(T&&!c)return!y.isDefined(a.isAsync)&&4>s("ff")&&(a.isAsync=!0),V.get(D?D(a):a);var E=a.headers;if(w&&(!E||!E.hasOwnProperty("X-Requested-With")))E=a.headers=E||{},E["X-Requested-With"]=null;if(e){var K=a.callbackParamName||"callback.html",B=a.callbackElementName||
"textarea",F,L,G,M,N=g.elements?g.elements.length:0,P;if(d=a.content)for(F in d)if(G=d[F],y.isDefined(G)){L=null;for(M=0;M<N;M++)if(P=g.elements[M],P.name===F){L=P;break}L?L.value=G:f?g.append(F,G):g.appendChild(R.create("input",{type:"hidden",name:F,value:G}))}if(s("esri-file-upload"))x.forEach(g.elements,function(a){a.name===K&&g.removeChild(a)}),a.contentType=!1,a.postData=f?g:new FormData(g),delete a.form;else{g.enctype="multipart/form-data";9>s("ie")&&(g.encoding="multipart/form-data");g.method=
"post";x.some(g.elements,function(a){return a.name===K})||g.appendChild(R.create("input",{type:"hidden",name:K,value:B}));if(-1!==k.toLowerCase().indexOf("addattachment")||-1!==k.toLowerCase().indexOf("updateattachment"))a.url=k+(-1===k.indexOf("?")?"?":"\x26")+K+"\x3d"+B,C&&(a.url=v+"?"+a.url);delete a.content}}if(w&&!a.hasOwnProperty("withCredentials"))if(f=C?v:k,-1!==x.indexOf(m.webTierAuthServers,J(f)))a.withCredentials=!0;else if(l.id){var H=l.id.findServerInfo(f);H&&H.webTierAuth&&(a.withCredentials=
!0)}a=D?D(a):a;return c?e&&!s("esri-file-upload")?W.send(a):z.post(a):z.get(a)}catch(O){return e=new Q,e.errback(a.error(O)),e}}function N(a){var d=m._processedCorsServers,e=-1,e=q.canUseXhr(a,!0);-1<e&&m.corsEnabledServers.splice(e,1);d[J(a)]=1;return e}function H(a){var d=m._processedCorsServers;if(m.corsDetection&&m.useCors)try{var e=J(a);s("esri-cors")&&(a&&-1!==a.toLowerCase().indexOf("/rest/services")&&!q.hasSameOrigin(a,window.location.href)&&!q.canUseXhr(a)&&!d[e])&&(d[e]=-1,z.get({url:a.substring(0,
a.toLowerCase().indexOf("/rest/")+6)+"info",content:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null}}).then(function(f){f?(d[e]=2,q.canUseXhr(a)||m.corsEnabledServers.push(e)):d[e]=1},function(a){d[e]=1}))}catch(f){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}}function n(a,d){function e(b){b._pendingDfd=B(a,d,A,r);if(!b._pendingDfd){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;var c=Error("Deferred object is missing");c.log=I.isDebug;
a._usrDfd=null;b.errback(c);b._pendingDfd=null;return b}b._pendingDfd.addCallback(function(d){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;a._usrDfd=null;b.callback(d);b._pendingDfd=null}).addErrback(function(c){var e,f,g;c&&(e=c.code,f=c.subcode,g=(g=c.messageCode)&&g.toUpperCase());if(c&&403==e&&(4==f||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!a._ssl){a._ssl=a._sslFromServer=!0;a._usrDfd=b;n(a,d);return}}else if(c&&415==c.status){if(N(a.url),
!a._err415){a._err415=1;a._usrDfd=b;n(a,d);return}}else if(l.id&&-1!==x.indexOf(l.id._errorCodes,e)&&!l.id._isPublic(a.url)&&!p&&(403!=e||-1===x.indexOf(Z,g)&&(!y.isDefined(f)||2==f))){b._pendingDfd=l.id.getCredential(a.url,{token:a._token,error:c});b._pendingDfd.addCallback(function(c){a._token=c.token;a._usrDfd=b;a._credential=c;a._ssl=a._sslFromServer||c.ssl;n(a,d)}).addErrback(function(c){a._usrDfd=null;b.errback(c);b._pendingDfd=null});return}b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;a._usrDfd=
null;b.errback(c);b._pendingDfd=null})}a.url=q.fixUrl(a.url);d=d||{};var f,h=a.form,p=d.disableIdentityLookup,t=d._preLookup,k=!1;if(s("esri-workers")&&!1!==m.useWorkers)if(!0===d.useWorkers||!0===m.useWorkers)k=!0;else if(d.workerOptions){var g=d.workerOptions;if(g.callback||g.worker&&g.worker.worker instanceof Worker)k=!0}var r=h&&h.append,A=h&&(h.elements?x.some(h.elements,function(a){return"file"===a.type}):r),u=-1!==a.url.toLowerCase().indexOf("token\x3d")||a.content&&a.content.token||A&&x.some(h.elements,
function(a){return"token"===a.name})?1:0;H(a.url);if(a._usrDfd)f=a._usrDfd;else{f=new Q(Y._dfdCanceller);f.addCallback(function(b){/\/sharing\/rest\/accounts\/self/i.test(a.url)&&(!u&&!a._token&&b.user&&b.user.username)&&m.webTierAuthServers.push(J(a.url));if(b=a._credential){var c=l.id.findServerInfo(b.server);if(c=c&&c.owningSystemUrl)c=c.replace(/\/?$/,"/sharing"),(b=l.id.findCredential(c,b.userId))&&-1===l.id._getIdenticalSvcIdx(c,b)&&b.resources.splice(0,0,c)}});f.addBoth(function(b){delete a._credential;
if(b&&(!s("ie")||!b.nodeType))b._ssl=a._ssl});var v=a.load,w=a.error;v&&f.addCallback(function(a){var c=f._pendingDfd,c=c&&c.ioArgs;return v.call(c&&c.args,a,c)});w&&f.addErrback(function(a){var c=f._pendingDfd,c=c&&c.ioArgs;return w.call(c&&c.args,a,c)})}if(l.id&&!u&&!a._token&&!l.id._isPublic(a.url)&&(!p||t))if(h=l.id.findCredential(a.url))a._token=h.token,a._ssl=h.ssl;k?d.workerOptions&&d.workerOptions.worker?(z=d.workerOptions.worker,e(f)):require(["esri/workers/RequestClient"],function(a){if(d.workerOptions){var c=
d.workerOptions;z=a.getClient(c.callback,c.cbFunction)}else z=a.getClient();e(f)}):e(f);return f}var D,m=X.defaults.io,Z=["COM_0056","COM_0057"];n._request=B;n._disableCors=N;n._detectCors=H;n.setRequestPreCallback=function(a){D=a};return n});