//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/Deferred","dojo/_base/array","dojo/_base/json","dojo/_base/config","dojo/has","dojo/io-query","esri/kernel","esri/config","esri/lang","esri/request","esri/deferredUtils","esri/urlUtils","esri/geometry/Extent","esri/geometry/Point","esri/SpatialReference","esri/layers/MosaicRule","esri/layers/DynamicMapServiceLayer","esri/layers/TimeInfo","esri/layers/Field","esri/graphic","esri/tasks/ImageServiceIdentifyTask","esri/tasks/ImageServiceIdentifyParameters"],function(D,d,p,m,t,w,
M,E,N,B,y,u,n,q,C,F,O,r,G,H,I,J,K,L){return D(G,{declaredClass:"esri.layers.ArcGISImageServiceLayer",_eventMap:{"rendering-change":!0,"mosaic-rule-change":!0},constructor:function(a,c){this._url=q.urlToObject(a);var b=c&&c.imageServiceParameters;this.format=b&&b.format;this.interpolation=b?b.interpolation:null;this.compressionQuality=b?b.compressionQuality:null;this.bandIds=b?b.bandIds:null;this.mosaicRule=b?b.mosaicRule:null;this.renderingRule=b?b.renderingRule:null;this._params=d.mixin({},this._url.query,
{f:"image",interpolation:this.interpolation,format:this.format,compressionQuality:this.compressionQuality,bandIds:this.bandIds?this.bandIds.join(","):null},b?b.toJson():{});this._initLayer=d.hitch(this,this._initLayer);this._queryVisibleRastersHandler=d.hitch(this,this._queryVisibleRastersHandler);this._visibleRasters=[];this.useMapImage=c&&c.useMapImage||!1;this.infoTemplate=c&&c.infoTemplate;this._rasterAttributeTableFields=[];this._rasterAttributeTableFeatures=[];this._loadCallback=c&&c.loadCallback;
(b=c&&c.resourceInfo)?this._initLayer(b):u({url:this._url.path,content:d.mixin({f:"json"},this._url.query),callbackParamName:"callback",load:this._initLayer,error:this._errorHandler});this.registerConnectEvents()},disableClientCaching:!1,_initLayer:function(a,c){this._findCredential();(this.credential&&this.credential.ssl||a&&a._ssl)&&this._useSSL();var b=this.minScale,g=this.maxScale;d.mixin(this,a);this.minScale=b;this.maxScale=g;this.initialExtent=this.fullExtent=this.extent=new C(a.extent);this.spatialReference=
this.initialExtent.spatialReference;this.pixelSizeX=parseFloat(this.pixelSizeX);this.pixelSizeY=parseFloat(this.pixelSizeY);for(var f=this.minValues,k=this.maxValues,e=this.meanValues,l=this.stdvValues,h=this.bands=[],b=0,g=this.bandCount;b<g;b++)h[b]={min:f[b],max:k[b],mean:e[b],stddev:l[b]};this.timeInfo=(b=this.timeInfo)&&b.timeExtent?new H(b):null;g=this.fields=[];if(f=a.fields)for(b=0;b<f.length;b++)g.push(new I(f[b]));this.version=a.currentVersion;this.version||(this.version="fields"in a||"objectIdField"in
a||"timeInfo"in a?10:9.3);y.isDefined(a.minScale)&&!this._hasMin&&this.setMinScale(a.minScale);y.isDefined(a.maxScale)&&!this._hasMax&&this.setMaxScale(a.maxScale);b={};a.defaultMosaicMethod?(b.method=a.defaultMosaicMethod,b.operation=a.mosaicOperator,b.sortField=a.sortField,b.sortValue=a.sortValue):b.method=r.METHOD_NONE;this.defaultMosaicRule=new r(b);this.defaultMosaicRule.ascending=!0;10<this.version&&this.hasRasterAttributeTable&&this.getRasterAttributeTable().then(d.hitch(this,function(a){a&&
(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=d.clone(a.features));a&&(a.fields&&0<a.fields.length)&&(this._rasterAttributeTableFields=d.clone(a.fields))}));this.loaded=!0;this.onLoad(this);if(b=this._loadCallback)delete this._loadCallback,b(this)},getKeyProperties:function(){var a=this._url.path+"/keyProperties",c=new p(n._dfdCanceller);10<this.version?(c._pendingDfd=u({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(a){c.callback(a)},
function(a){c.errback(a)})):(a=Error("Layer does not have key properties"),a.log=w.isDebug,c.errback(a));return c},getRasterAttributeTable:function(){var a=this._url.path+"/rasterAttributeTable",c=new p(n._dfdCanceller);10<this.version&&this.hasRasterAttributeTable?(c._pendingDfd=u({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(a){c.callback(a)},function(a){c.errback(a)})):(a=Error("Layer does not support raster attribute table"),a.log=w.isDebug,
c.errback(a));return c},_getRasterAttributeTableFeatures:function(){var a=new p;if(this._rasterAttributeTableFeatures&&0<this._rasterAttributeTableFeatures.length)return a.resolve(this._rasterAttributeTableFeatures),a;if(10<this.version&&this.hasRasterAttributeTable)return a=this.getRasterAttributeTable(),a.then(d.hitch(this,function(a){a&&(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=d.clone(a.features))})),a;a.resolve(this._rasterAttributeTableFeatures);return a},getCustomRasterFields:function(a){var c=
a?a.rasterAttributeTableFieldPrefix:"",b={name:"Raster.ItemPixelValue",alias:"Item Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};a=this.fields?d.clone(this.fields):[];var g=a.length;a[g]={name:"Raster.ServicePixelValue",alias:"Service Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};this.capabilities&&-1<this.capabilities.toLowerCase().indexOf("catalog")&&(a[g+1]=b);this._rasterAttributeTableFields&&0<this._rasterAttributeTableFields.length&&
(b=m.filter(this._rasterAttributeTableFields,function(a){return"esriFieldTypeOID"!==a.type&&"value"!==a.name.toLowerCase()}),b=m.map(b,function(a){var b=d.clone(a);b.name=c+a.name;return b}),a=a.concat(b));return a},getImageUrl:function(a,c,b,g){var f=a.spatialReference.wkid||t.toJson(a.spatialReference.toJson());delete this._params._ts;var k=this._url.path+"/exportImage?";d.mixin(this._params,{bbox:a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,imageSR:f,bboxSR:f,size:c+","+b},this.disableClientCaching?
{_ts:(new Date).getTime()}:{});var e=this._params.token=this._getToken();a=q.addProxy(k+E.objectToQuery(d.mixin(this._params,{f:"image"})));a.length>B.defaults.io.postLength||this.useMapImage?this._jsonRequest=u({url:k,content:d.mixin(this._params,{f:"json"}),callbackParamName:"callback",load:function(a,b){var c=a.href;e&&(c+=-1===c.indexOf("?")?"?token\x3d"+e:"\x26token\x3d"+e);g(q.addProxy(c))},error:this._errorHandler}):g(a)},onRenderingChange:function(){},onMosaicRuleChange:function(){},setInterpolation:function(a,
c){this.interpolation=this._params.interpolation=a;c||this.refresh(!0)},setCompressionQuality:function(a,c){this.compressionQuality=this._params.compressionQuality=a;c||this.refresh(!0)},setBandIds:function(a,c){var b=!1;this.bandIds!==a&&(b=!0);this.bandIds=a;this._params.bandIds=a.join(",");if(b&&!c)this.onRenderingChange();c||this.refresh(!0)},setDefaultBandIds:function(a){this.bandIds=this._params.bandIds=null;a||this.refresh(!0)},setDisableClientCaching:function(a){this.disableClientCaching=
a},setMosaicRule:function(a,c){var b=!1;this.mosaicRule!==a&&(b=!0);this.mosaicRule=a;this._params.mosaicRule=t.toJson(a.toJson());if(b&&!c)this.onMosaicRuleChange();c||this.refresh(!0)},setRenderingRule:function(a,c){var b=!1;this.renderingRule!==a&&(b=!0);this.renderingRule=a;this._params.renderingRule=a?t.toJson(a.toJson()):null;if(b&&!c)this.onRenderingChange();c||this.refresh(!0)},setImageFormat:function(a,c){this.format=this._params.format=a;c||this.refresh(!0)},setInfoTemplate:function(a){this.infoTemplate=
a},setDefinitionExpression:function(a,c){var b=this.mosaicRule?this.mosaicRule.toJson():{};this.mosaicRule||(this.defaultMosaicRule?b=this.defaultMosaicRule.toJson():b.method=r.METHOD_NONE);b.where=a;b=new r(b);this.setMosaicRule(b,c);return this},getDefinitionExpression:function(){return this.mosaicRule?this.mosaicRule.where:null},refresh:function(a){if(a)this.inherited(arguments);else{var c=this.disableClientCaching;this.disableClientCaching=!0;this.inherited(arguments);this.disableClientCaching=
c}},exportMapImage:function(a,c){var b=B.defaults.map,b=d.mixin({size:b.width+","+b.height},this._params,a?a.toJson(this.normalization):{},{f:"json"});delete b._ts;this._exportMapImage(this._url.path+"/exportImage",b,c)},queryVisibleRasters:function(a,c,b,g){var f=this._map,d=n._fixDfd(new p(n._dfdCanceller));this._visibleRasters=[];var e,l,h=!0;if(this.infoTemplate&&this.infoTemplate.info.fieldInfos&&0<this.infoTemplate.info.fieldInfos.length){h=!1;for(e=0;e<this.infoTemplate.info.fieldInfos.length;e++)(l=
this.infoTemplate.info.fieldInfos[e])&&(l.visible&&"raster.servicepixelvalue"!==l.fieldName.toLowerCase())&&(h=!0)}e=new L;e.geometry=a.geometry.getCenter();e.returnGeometry=!0;e.returnCatalogItems=h;e.timeExtent=a.timeExtent;e.mosaicRule=this.mosaicRule?this.mosaicRule:null;e.renderingRule=this.renderingRule?this.renderingRule:null;f&&(a=new F((f.extent.xmax-f.extent.xmin)/(2*f.width),(f.extent.ymax-f.extent.ymin)/(2*f.height),f.extent.spatialReference),e.pixelSize=a);var m=this;a=new K(this.url);
(d._pendingDfd=a.execute(e)).addCallbacks(function(a){m._queryVisibleRastersHandler(a,c,b,g,d)},function(a){m._resolve([a],null,g,d,!0)});return d},_queryVisibleRastersHandler:function(a,c,b,g,f){var k=a.features,e=a.value,l;a.catalogItems&&(k=a.catalogItems.features,l=a.properties.Values);this._visibleRasters=[];var h;a=-1<e.toLowerCase().indexOf("nodata");e&&(!k&&!a)&&(k=[],h=new J(new C(this.fullExtent),null,{ObjectId:0}),k.push(h));var n=[];if(k){a=this.getCustomRasterFields(c);var p=this._getDomainFields(a),
u=c?c.returnDomainValues:!1,r=c&&c.rasterAttributeTableFieldPrefix,v,x,t,q,s,z,w,A;this._getRasterAttributeTableFeatures().then(d.hitch(this,function(a){for(v=0;v<k.length;v++){h=k[v];h.setInfoTemplate(this.infoTemplate);if(e&&(x=e,l&&l.length>=v&&(t=l[v],x=t.replace(/ /gi,", ")),h.attributes["Raster.ItemPixelValue"]=x,h.attributes["Raster.ServicePixelValue"]=e,a&&0<a.length&&(q=m.filter(a,function(a){if(a&&a.attributes)return a.attributes.hasOwnProperty("Value")?a.attributes.Value==x:a.attributes.VALUE==
x}),0<q.length&&(s=d.clone(q[0]),r&&s)))){A={};for(z in s.attributes)s.attributes.hasOwnProperty(z)&&(w=r+z,A[w]=s.attributes[z]);s.attributes=A;h.attributes=d.mixin(h.attributes,s.attributes)}u&&(p&&0<p.length)&&m.forEach(p,function(a){if(a){var b=h.attributes[a.name];y.isDefined(b)&&(b=this._getDomainValue(a.domain,b),y.isDefined(b)&&(h.attributes[a.name]=b))}},this);n.push(h);this._visibleRasters.push(h)}this._resolve([n,null,!0],null,b,f)}))}else this._resolve([n,null,null],null,b,f)},getVisibleRasters:function(){var a=
this._visibleRasters,c=[],b;for(b in a)a.hasOwnProperty(b)&&c.push(a[b]);return c},_getDomainFields:function(a){if(a){var c=[];m.forEach(a,function(a){if(a.domain){var g={};g.name=a.name;g.domain=a.domain;c.push(g)}});return c}},_getDomainValue:function(a,c){if(a&&a.codedValues){var b;m.some(a.codedValues,function(a){return a.code===c?(b=a.name,!0):!1});return b}},_resolve:function(a,c,b,d,f){c&&this[c].apply(this,a);b&&b.apply(null,a);d&&n._resDfd(d,a,f)}})});