//>>built
define(["dojo/_base/declare","dojo/_base/connect","dojo/_base/lang","dojo/_base/array","dojo/_base/url","dojo/dom-construct","dojo/dom-class","dojo/dom-geometry","dojo/dom-style","dojox/collections/ArrayList","dojox/gfx/matrix","esri/kernel","esri/config","esri/sniff","esri/domUtils","esri/tileUtils","esri/geometry/Point","esri/geometry/Rect","esri/layers/layer"],function(Q,m,B,y,F,r,J,K,l,L,M,t,R,v,N,C,O,D,S){var z=R.defaults.map.zoomDuration;return Q(S,{declaredClass:"esri.layers.TiledMapServiceLayer",constructor:function(a,
c){m.connect(this,"onLoad",this,"_initTiledLayer");this._lowestLevel=(this._displayLevels=c?c.displayLevels:null)?this._displayLevels[0]:0;this.resampling=c?c.resampling:!1;this._resamplingTolerance=c?c.resamplingTolerance:null;var d=B.hitch;this._addImage=d(this,this._addImage);this._tileLoadHandler=d(this,this._tileLoadHandler);this._tileErrorHandler=d(this,this._tileErrorHandler);this._tilePopPop=d(this,this._tilePopPop);this._cleanUpRemovedImages=d(this,this._cleanUpRemovedImages);this._fireOnUpdateEvent=
d(this,this._fireOnUpdateEvent);this._transitionEnd=d(this,this._transitionEnd)},opacity:1,isPNG32:!1,_multiple:1,_initTiledLayer:function(){var a=this.tileInfo,c=a.lods;this._tileW=a.width;this._tileH=a.height;var d=this.scales=[],b=this._displayLevels,e="esri.layers.WMTSLayer"===this.declaredClass&&96!=a.dpi,f=-Infinity,g=Infinity,h=this.fullExtent,l=new O(h.xmin,h.ymax),h=new O(h.xmax,h.ymin),k=C.getContainingTileCoords,n,p,q,r=c.length;for(q=0;q<r;q++)if(p=c[q],e&&(p.scale=96*p.scale/a.dpi),n=
k(a,l,p),p.startTileRow=0>n.row?0:n.row,p.startTileCol=0>n.col?0:n.col,n=k(a,h,p),p.endTileRow=n.row,p.endTileCol=n.col,!b||-1!==y.indexOf(b,p.level))d[q]=p.scale,f=p.scale>f?p.scale:f,g=p.scale<g?p.scale:g;e&&(a.dpi=96);-Infinity!==f&&!this._hasMin&&this.setMinScale(f);Infinity!==g&&!this._hasMax&&this.setMaxScale(g);this._patchIE=6<=v("ie")&&7>v("ie")&&(this.isPNG32||"Mixed"===a.format)},_isMapAtVisibleScale:function(){var a=this.inherited(arguments);if(a){var c;c=this._map;var a=this.scales,d=
c.getScale(),b=!1,e=c.width>c.height?c.width:c.height;for(c=0;c<a.length;c++)if(Math.abs(a[c]-d)/a[c]<1/e){b=!0;break}a=b}return a},_setMap:function(a,c,d,b){this.inherited(arguments);this._map=a;var e=this._div=r.create("div",null,c),f=a.__visibleDelta,g=m.connect,h=t._css.names,u={position:"absolute",width:a.width+"px",height:a.height+"px",overflow:"visible"};"css-transforms"===a.navigationMode?(u[h.transform]=t._css.translate(-f.x,-f.y),l.set(e,u),delete u[h.transform],u[h.transition]=h.transformName+
" "+z+"ms ease",l.set(this._active=r.create("div",null,e),u),this._active._remove=0,this._passives=[]):(u.left=-f.x+"px",u.top=-f.y+"px",l.set(e,u));this._onResizeHandler_connect=g(a,"onResize",this,"_onResizeHandler");this._opacityChangeHandler_connect=g(this,"onOpacityChange",this,"_opacityChangeHandler");f=this.tileInfo;g=f.spatialReference;h=g._getInfo();(this._wrap=a.wrapAround180&&g._isWrappable()&&Math.abs(h.origin[0]-f.origin.x)<=h.dx)&&C._addFrameInfo(f,h);this.evaluateSuspension();if(this.suspended&&
!a.loaded)var k=m.connect(a,"onLoad",this,function(){m.disconnect(k);k=null;this.evaluateSuspension()});return e},_unsetMap:function(a,c){this.suspended||this._suspendImpl();r.destroy(this._div);this._map=this._div=null;var d=m.disconnect;d(this._onResizeHandler_connect);d(this._opacityChangeHandler_connect);this.inherited(arguments)},onSuspend:function(){this.inherited(arguments);this._suspendImpl()},_suspendImpl:function(){N.hide(this._div);clearTimeout(this._wakeTimer);this._wakeTimer=null;this._disableDrawConnectors();
var a=this._tiles,c=this._tileIds,d=this._loadingList,b,e,f=m.disconnect,g=r.destroy;d&&0<d.count&&(d.forEach(function(c){if(b=a[c])f(b._onload_connect),f(b._onerror_connect),f(b._onabort_connect),b._onload_connect=b._onerror_connect=b._onabort_connect=null}),d.clear(),this._fireUpdateEnd());this._removeList.clear();for(d=c.length-1;0<=d;d--)(b=(e=c[d])&&a[e])&&g(b);if("css-transforms"===this._map.navigationMode){c=this._active;e=this._passives;var h;this._noDom=0;for(d=e.length-1;0<=d;d--)h=e[d],
h._endHandle&&f(h._endHandle),h._matrix=h._multiply=h._endHandle=null,h._marked=h._remove=0,e.splice(d,1),g(h);c._matrix=c._multiply=null;c._marked=c._remove=0}this._tileIds=this._tiles=this._tileBounds=this._ct=this._loadingList=this._removeList=this._standby=null},onResume:function(){this.inherited(arguments);this._tileIds=[];this._tiles=[];this._tileBounds=[];this._ct=null;this._removeList=new L;this._loadingList=new L;N.show(this._div);this._enableDrawConnectors();this._wakeTimer=this._wakeTimer||
setTimeout(B.hitch(this,function(){this.suspended||this._onExtentChangeHandler(this._map.extent,null,!0,this._map.__LOD)}),0)},_enableDrawConnectors:function(){var a=this._map,c=m.connect;if("css-transforms"===a.navigationMode){if(this._onScaleHandler_connect=c(a,"onScale",this,this._onScaleHandler),v("esri-touch")||v("esri-pointer")){this._standby=[];var d=this,b=function(){d._noDom=1};this._onPanStartHandler_connect=c(a,"onPanStart",b);this._onZoomStartHandler_connect=c(a,"onZoomStart",b)}}else this._onZoomHandler_connect=
c(a,"onZoom",this,"_onZoomHandler");this._onPanHandler_connect=c(a,"onPan",this,"_onPanHandler");this._onExtentChangeHandler_connect=c(a,"onExtentChange",this,"_onExtentChangeHandler")},_disableDrawConnectors:function(){var a=m.disconnect;a(this._onPanHandler_connect);a(this._onZoomHandler_connect);a(this._onScaleHandler_connect);a(this._onExtentChangeHandler_connect);a(this._onPanStartHandler_connect);a(this._onZoomStartHandler_connect);this._onPanHandler_connect=this._onZoomHandler_connect=this._onScaleHandler_connect=
this._onExtentChangeHandler_connect=this._onPanStartHandler_connect=this._onZoomStartHandler_connect=null},_onResizeHandler:function(a,c,d){a={width:c+"px",height:d+"px"};c=l.set;c(this._div,a);if("css-transforms"===this._map.navigationMode){this._active&&c(this._active,a);for(d=this._passives.length-1;0<=d;d--)c(this._passives[d],a)}},_onExtentChangeHandler:function(a,c,d,b){c=this._map;var e=this._standby,f;clearTimeout(this._wakeTimer);this._wakeTimer=null;if(!c._isPanningOrZooming()){if("css-transforms"===
c.navigationMode){if(d)for(b=this._passives.length-1;0<=b;b--)f=this._passives[b],l.set(f,t._css.names.transition,"none"),f._marked?(this._passives.splice(b,1),f.parentNode&&f.parentNode.removeChild(f),r.destroy(f)):0<f.childNodes.length&&(f._multiply=f._multiply?M.multiply(f._matrix,f._multiply):f._matrix);this._noDom=0;if(e&&e.length)for(b=e.length-1;0<=b;b--)f=e[b],l.set(f,"visibility","visible"),this._tilePopPop(f),e.splice(b,1)}this._fireUpdateStart();this._rrIndex=0;b=C.getCandidateTileInfo(c,
this.tileInfo,a);a=c.__visibleDelta;if(!this._ct||b.lod.level!==this._ct.lod.level||d){f=b&&this._ct&&b.lod.level!==this._ct.lod.level;this._ct=b;var g=this._tiles,h=this._tileIds,u=this._tileBounds,k=this._removeList,n,p=h.length;this._cleanUpRemovedImages();for(b=0;b<p;b++)e=h[b],n=g[e],u[e]=h[b]=null,"css-transforms"===c.navigationMode&&(f&&n.parentNode&&c.fadeOnZoom)&&(n._fadeOut=f,n.parentNode._remove++),k.add(n);d&&(this._tileIds=[],this._tiles=[],this._tileBounds=[])}b=a.x;d=a.y;"css-transforms"===
c.navigationMode?(e={},e[t._css.names.transform]=t._css.translate(b,d),l.set(this._div,e)):l.set(this._div,{left:b+"px",top:d+"px"});this.__coords_dx=b;this.__coords_dy=d;this._updateImages(new D(0,0,a.width,a.height));0===this._loadingList.count?(this.onUpdate(),this._fireUpdateEnd()):this._fireOnUpdate=!0;d=this._tileW;g=this._tileH;a=new D(-a.x,-a.y,a.width,a.height);for(b=this._tileIds.length-1;0<=b;b--)(e=this._tileIds[b])?(f=this._tiles[e],h=K.getMarginBox(f),h=new D(h.l,h.t,d,g),"css-transforms"===
c.navigationMode&&(h.x=f._left,h.y=f._top),a.intersects(h)?this._tileBounds[e]=h:(this._loadingList.contains(e)&&this._tilePopPop(f),r.destroy(f),this._tileIds.splice(b,1),delete this._tileBounds[e],delete this._tiles[e])):(this._tileIds.splice(b,1),delete this._tileBounds[e],delete this._tiles[e])}},_onPanHandler:function(a,c){var d=this._map,b=d.__visibleDelta.offset(c.x,c.y);this.__coords_dx=this.__coords_dy=0;"css-transforms"===d.navigationMode?(d={},d[t._css.names.transform]=t._css.translate(b.x,
b.y),l.set(this._div,d),!v("esri-touch")&&!v("esri-pointer")&&this._updateImages({x:-b.x,y:-b.y,width:b.width,height:b.height})):(l.set(this._div,{left:b.x+"px",top:b.y+"px"}),this._updateImages({x:-b.x,y:-b.y,width:b.width,height:b.height}));0<this._loadingList.count&&(this._fireUpdateStart(),this._fireOnUpdate=!0)},_onScaleHandler:function(a,c){var d,b={},e=t._css.names,f=this._map;for(d=this._passives.length-1;0<=d;d--){var g=this._passives[d];0===g.childNodes.length?(this._passives.splice(d,1),
r.destroy(g)):("none"===g.style[e.transition]&&l.set(g,e.transition,e.transformName+" "+z+"ms ease"),l.set(g,e.transition,c?"none":e.transformName+" "+z+"ms ease"),g._matrix=a,b[e.transform]=t._css.matrix(g._multiply?M.multiply(a,g._multiply):a),l.set(g,b))}this._active&&0===this._active.childNodes.length||(l.set(this._active,e.transition,c?"none":e.transformName+" "+z+"ms ease"),this._active._matrix=a,b[e.transform]=t._css.matrix(this._active._matrix),l.set(this._active,b),this._passives.push(this._active),
b={position:"absolute",width:f.width+"px",height:f.height+"px",overflow:"visible"},b[e.transition]=e.transformName+" "+z+"ms ease",l.set(this._active=r.create("div",null,this._div),b),this._active._remove=0,f.fadeOnZoom&&r.place(this._active,this._div,"first"))},_onZoomHandler:function(a,c,d){a=K.getMarginBox(this._div);d=d.offset(-a.l,-a.t);if(!this._previousScale||1===c)this._previousScale=1;var b,e=this._tileW*c,f=this._tileH*c,g=this._tileBounds,h=this._tiles,u=this._previousScale,k=this._multiple,
n=l.set,p,q;if((a=v("ie"))&&8>a)y.forEach(this._tileIds,function(a){q="";b=g[a];p=h[a].style.margin.split(" ");y.forEach(p,function(a){""!==q&&(q+=" ");a=parseFloat(a);q+=a/u*c+"px"});n(h[a],{left:b.x-(e-b.width)*(d.x-b.x)/b.width+"px",top:b.y-(f-b.height)*(d.y-b.y)/b.height+"px",margin:1!==k&&-1===q.indexOf("NaN")?q:"",zoom:c})});else{var r=e*k,t=f*k,P,m;y.forEach(this._tileIds,function(a){q="";b=g[a];P=b.x-(e-b.width)*(d.x-b.x)/b.width;m=b.y-(f-b.height)*(d.y-b.y)/b.height;p=h[a].style.margin.split(" ");
y.forEach(p,function(a){""!==q&&(q+=" ");a=parseFloat(a);q+=a/u*c+"px"});n(h[a],{left:P+"px",top:m+"px",margin:1!==k&&-1===q.indexOf("NaN")?q:"",width:r+"px",height:t+"px"})})}this._previousScale=c},_updateImages:function(a){if(this._ct){var c,d=this._tileW,b=this._tileH,e=this._ct;c=e.lod;var e=e.tile,f=e.offsets,g=e.coords,h=g.row,g=g.col,l=c.level,k=this.opacity,n=this._tileIds,p=this._loadingList,q=this._addImage,r=this._map.id,t=this.id,m=a.x,v=a.y,z=c.startTileRow,B=c.endTileRow,C=c.startTileCol,
D=c.endTileCol,F=y.indexOf,x,s,H=f.x-this.__coords_dx,E=f.y-this.__coords_dy;s=d-H+-a.x;var w=b-E+-a.y;x=Math.ceil;s=0<s?s%d:d-Math.abs(s)%d;w=0<w?w%b:b-Math.abs(w)%b;m=0<m?Math.floor((m+H)/d):x((m-(d-H))/d);v=0<v?Math.floor((v+E)/b):x((v-(b-E))/b);E=m+x((a.width-s)/d);a=v+x((a.height-w)/b);var A,G,I;this._wrap&&(A=c._frameInfo,G=A[0],I=A[1],A=A[2]);for(w=m;w<=E;w++)for(m=v;m<=a;m++)x=h+m,s=g+w,this._wrap&&(s<I?(s%=G,s=s<I?s+G:s):s>A&&(s%=G)),x>=z&&(x<=B&&s>=C&&s<=D)&&(c=r+"_"+t+"_tile_"+l+"_"+m+
"_"+w,-1===F(n,c)&&(p.add(c),n.push(c),q(l,m,x,w,s,c,d,b,k,e,f)))}},_cleanUpRemovedImages:function(){var a=this._removeList,c=r.destroy,d,b=t._css.names;a.forEach(function(a){a._fadeOut||(a.style.filter="",a.style.zoom=1,c(a))});if("css-transforms"===this._map.navigationMode)for(d=this._passives.length-1;0<=d;d--){var e=this._passives[d];0===e.childNodes.length?(this._passives.splice(d,1),c(e)):this._map.fadeOnZoom&&(!e._marked&&e._remove===e.childNodes.length)&&(l.set(e,b.transition,"opacity 0.65s"),
l.set(e,"opacity",0),e._marked=1,10<=v("ie")?e.addEventListener(b.endEvent,this._transitionEnd,!1):e._endHandle=m.connect(e,b.endEvent,this._transitionEnd))}a.clear()},_transitionEnd:function(a){var c=a.target;"opacity"===a.propertyName&&(10<=v("ie")?c.removeEventListener(t._css.names.endEvent,this._transitionEnd,!1):(m.disconnect(c._endHandle),c._endHandle=null),a=y.indexOf(this._passives,c),-1<a&&this._passives.splice(a,1),c.parentNode&&c.parentNode.removeChild(c),r.destroy(c))},_addImage:function(a,
c,d,b,e,f,g,h,u,k,n){if(this._patchIE)k=this._tiles[f]=r.create("div"),k.id=f,J.add(k,"layerTile"),l.set(k,{left:g*b-n.x+"px",top:h*c-n.y+"px",width:g+"px",height:h+"px",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src\x3d'"+this.getTileUrl(a,d,e)+"', sizingMethod\x3d'scale')"}),1>u&&l.set(k,"opacity",u),a=k.appendChild(r.create("div")),l.set(a,{opacity:0,width:g+"px",height:h+"px"}),this._div.appendChild(k),this._loadingList.remove(f),this._fireOnUpdateEvent();else{k=this._tiles[f]=
r.create("img");var p=m.connect;k.id=f;J.add(k,"layerTile");f=g*b-n.x;n=h*c-n.y;c=this._map;b=t._css.names;g={width:g+"px",height:h+"px",visibility:"hidden"};"css-transforms"===c.navigationMode?(g[b.transform]=t._css.translate(f,n),l.set(k,g),k._left=f,k._top=n):(g.left=f+"px",g.top=n+"px",l.set(k,g));1>u&&l.set(k,"opacity",u);k._onload_connect=p(k,"onload",this,"_tileLoadHandler");k._onerror_connect=p(k,"onerror",B.hitch(this,"_tileErrorHandler",d,e));k._onabort_connect=p(k,"onabort",this,"_tileAbortHandler");
if(a=this.getTileUrl(a,d,e,k))this._failedRequests&&this._failedRequests[a]?(l.set(k,this._failedRequests[a].css),k.src=this._failedRequests[a].src,this._multiple=parseInt(this._failedRequests[a].css.width)/this._tileW):(this._multiple=1,k.src=a);"css-transforms"===c.navigationMode?this._active.appendChild(k):this._div.appendChild(k)}},getTileUrl:function(a,c,d){},_reCheckTS:/[\?\&]_ts=/ig,_reReplaceTS:/([\?\&]_ts=)[0-9]+/ig,addTimestampToURL:function(a){var c=this._refreshTS;c&&(a=this._reCheckTS.test(a)?
a.replace(this._reReplaceTS,"$$$1"+c):a+((-1===a.indexOf("?")?"?":"\x26")+"_ts\x3d"+c));return a},refresh:function(){this.suspended||(this._refreshTS=(new Date).getTime(),this._onExtentChangeHandler(this._map.extent,null,!0,this._map.__LOD))},_tilePopPop:function(a){var c=m.disconnect;c(a._onload_connect);c(a._onerror_connect);c(a._onabort_connect);a._onload_connect=a._onerror_connect=a._onabort_connect=null;this._loadingList.remove(a.id);this._fireOnUpdateEvent()},_tileLoadHandler:function(a){a=
a.currentTarget;this._noDom?this._standby.push(a):(l.set(a,"visibility","visible"),this._tilePopPop(a))},_tileAbortHandler:function(a){a=a.currentTarget;this.onError(Error("Unable to load tile: "+a.src));l.set(a,"visibility","hidden");this._tilePopPop(a)},_tileErrorHandler:function(a,c,d){d=d.currentTarget;var b=(new F(d.src)).path.split("/"),b=parseInt(b[b.length-3]);this._multiple=Math.pow(2,this._ct.lod.level-b+1);!this.resampling||b===this._lowestLevel||0===this._resamplingTolerance||this._resamplingTolerance&&
Math.log(this._multiple)/Math.LN2>this._resamplingTolerance?(this.onError(Error("Unable to load tile: "+d.src)),l.set(d,"visibility","hidden"),this._tilePopPop(d)):this._resample(d,a,c)},_resample:function(a,c,d){var b=(new F(a.src)).path.split("/"),e=this._multiple,f=parseInt(b[b.length-3])-1,g=parseInt(c/e),h=parseInt(d/e),b=d%e,m=c%e,g=this.getTileUrl(f,g,h);c=this.getTileUrl(f+Math.log(e)/Math.LN2,c,d);e={width:this._tileW*e+"px",height:this._tileH*e+"px",margin:"-"+this._tileW*m+"px 0 0 "+("-"+
this._tileH*b+"px")};this._failedRequests||(this._failedRequests={});this._failedRequests[c]={src:g,css:e};l.set(a,e);v("chrome")&&a.setAttribute("src",null);a.src=g},_fireOnUpdateEvent:function(){0===this._loadingList.count&&(this._cleanUpRemovedImages(),this._fireOnUpdate&&(this._fireOnUpdate=!1,this.onUpdate(),this._fireUpdateEnd()))},setOpacity:function(a){if(this.opacity!=a)this.onOpacityChange(this.opacity=a)},onOpacityChange:function(){},_opacityChangeHandler:function(a){var c=l.set,d,b,e;
if("css-transforms"===this._map.navigationMode){if(this._active){e=this._active.childNodes;for(d=e.length-1;0<=d;d--)c(e[d],"opacity",a)}for(d=this._passives.length-1;0<=d;d--){e=this._passives[d].childNodes;for(b=e.length-1;0<=b;b--)c(e[b],"opacity",a)}}else{e=this._div.childNodes;for(d=e.length-1;0<=d;d--)c(e[d],"opacity",a)}}})});